import { test, expect } from "@playwright/test";
const OUT = "../../artifacts/screens";
test("capture screenshots for visual review", async ({ page, browser }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/"); await page.waitForTimeout(500);
  await page.screenshot({ path: `${OUT}/01-landing.png`, fullPage: false });
  await page.screenshot({ path: `${OUT}/01b-landing-full.png`, fullPage: true });
  await page.goto("/demo"); await expect(page.getByTestId("player")).toBeVisible();
  await page.screenshot({ path: `${OUT}/02-play.png`, fullPage: true });
  await page.locator('[data-evidence="e_guar"]').click(); await page.locator('[data-evidence="e_urgent"]').click();
  await page.locator('[data-action="invest"]').click();
  await page.locator("#why").fill("My friend invested so it is probably legit and it is guaranteed");
  await page.locator('[data-conf="5"]').click(); await page.getByTestId("decide").click();
  await expect(page.getByTestId("feedback")).toBeVisible(); await page.waitForTimeout(300);
  await page.screenshot({ path: `${OUT}/03-feedback.png`, fullPage: true });
  await page.getByTestId("continue").click();
  await page.locator('[data-action="stop_pay"]').click(); await page.getByTestId("decide").click();
  await page.getByTestId("continue").click();
  await expect(page.getByTestId("summary")).toBeVisible(); await page.waitForTimeout(300);
  await page.screenshot({ path: `${OUT}/04-summary.png`, fullPage: true });
  await page.goto("/resilience"); await page.waitForTimeout(500);
  await page.screenshot({ path: `${OUT}/05-resilience.png`, fullPage: true });
  await page.goto("/learn?tab=sims&sim=fee_erosion"); await page.waitForTimeout(800);
  await page.screenshot({ path: `${OUT}/06-sim.png`, fullPage: true });
  await page.goto("/learn?tab=concepts&concept=volatility"); await page.waitForTimeout(500);
  await page.screenshot({ path: `${OUT}/07-concepts.png`, fullPage: true });
  await page.goto("/progress"); await page.waitForTimeout(500);
  await page.screenshot({ path: `${OUT}/08-progress.png`, fullPage: true });
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const m = await ctx.newPage(); await m.emulateMedia({ reducedMotion: "reduce" });
  await m.goto("/"); await m.waitForTimeout(600); await m.screenshot({ path: `${OUT}/09-mobile-landing.png` });
  await m.goto("/demo"); await expect(m.getByTestId("player")).toBeVisible(); await m.screenshot({ path: `${OUT}/10-mobile-play.png`, fullPage: true });
  await ctx.close();
});
