from _lib import A, CH, E, END, L, P, ST, scenario

SC = scenario(
    id="guaranteed_opportunity",
    title=L("The Guaranteed Opportunity", "The Guaranteed Opportunity (Pakka Munafa?)", "गारंटीशुदा अवसर"),
    tagline=L("A Telegram message promises 30% returns. What do you do?",
              "Telegram pe message aaya: 30% returns ki guarantee. Aap kya karoge?",
              "टेलीग्राम पर संदेश: 30% रिटर्न की गारंटी। आप क्या करेंगे?"),
    character={"name": "Rahul", "age": 24, "role": "first-time investor, three months into his first job"},
    difficulty=1,
    concept_tags=["fraud_red_flags", "verification", "risk", "social_proof"],
    pressure_tags=["urgency", "scarcity", "authority", "social_proof", "greed", "loss_recovery", "countdown"],
    tests=["M001", "M002", "M005", "M006", "M007", "M009", "M010", "M011"],
    initial="s1_message",
    dimensions=["scam_awareness", "evidence_verification", "risk_recognition", "fomo_resistance", "herd_resistance"],
    states=[
        ST("s1_message",
           L("A message from a stranger", "Ek anjaan ka message", "अजनबी का संदेश"),
           L("Rahul is 24 and started his first job three months ago. An unknown number adds him to a Telegram group "
             "and posts this. Everything here is fictional — no real money is involved.",
             "Rahul 24 saal ka hai aur teen mahine pehle pehli job lagi hai. Ek anjaan number use Telegram group mein "
             "add karta hai aur ye message bhejta hai. Sab kuch kaalpanik hai — asli paisa shamil nahi hai.",
             "राहुल 24 साल का है और तीन महीने पहले उसकी पहली नौकरी लगी। एक अनजान नंबर उसे टेलीग्राम ग्रुप में जोड़कर "
             "यह संदेश भेजता है। सब कुछ काल्पनिक है — इसमें कोई असली पैसा नहीं है।"),
           channel=CH("telegram", "Aarav Mehta · WealthWave Circle (fictional)", [
               L("SEBI registered opportunity.", "SEBI registered opportunity.", "SEBI पंजीकृत अवसर।"),
               L("Guaranteed 30% returns.", "Guaranteed 30% returns.", "30% रिटर्न की गारंटी।"),
               L("Only 10 slots remaining.", "Sirf 10 slots bache hain.", "सिर्फ़ 10 स्लॉट बचे हैं।"),
               L("Invest today.", "Aaj hi invest karo.", "आज ही निवेश करें।")]),
           pressure=[
               P("urgency", L("“Invest today.”", "“Aaj hi invest karo.”", "“आज ही निवेश करें।”")),
               P("scarcity", L("Only 10 slots remaining.", "Sirf 10 slots bache hain.", "सिर्फ़ 10 स्लॉट बचे हैं।")),
               P("countdown", L("Your slot is held for a few more moments…", "Aapka slot thodi der ke liye roka gaya hai…",
                                "आपका स्लॉट कुछ देर के लिए रुका है…"), countdown=45)],
           evidence=[
               E("e_auth", L("“SEBI registered”", "“SEBI registered” ka daava", "“SEBI पंजीकृत” का दावा"),
                 L("A claim of registration, with no registration number and no way to check it.",
                   "Registration ka daava, par na koi number, na check karne ka tareeka.",
                   "पंजीकरण का दावा, पर न कोई नंबर, न जाँच का तरीका।"), "red_flag",
                 L("A claim of registration is not proof. Registration can be checked independently on the regulator's "
                   "official website. A claim inside a message from a stranger proves nothing by itself.",
                   "Registration ka daava saboot nahi hai. Ise regulator ki official website par khud check kiya ja sakta hai. "
                   "Anjaan ke message ka daava apne aap mein kuch sabit nahi karta.",
                   "पंजीकरण का दावा सबूत नहीं है। इसे नियामक की आधिकारिक वेबसाइट पर खुद जाँचा जा सकता है।"),
                 "authority_claim"),
               E("e_guar", L("“Guaranteed 30% returns”", "“Guaranteed 30% returns”", "“30% रिटर्न की गारंटी”"),
                 L("A fixed, high return is promised with no conditions.", "Bina kisi shart ke ek tay, ooncha return ka vaada.",
                   "बिना किसी शर्त के तय, ऊँचे रिटर्न का वादा।"), "red_flag",
                 L("Market-linked investments cannot honestly guarantee returns, and a promise this high usually means "
                   "high risk or a scam. Higher promised returns are not automatically a better opportunity.",
                   "Market se jude investments sach mein returns guarantee nahi kar sakte. Itna ooncha vaada aksar bada risk ya "
                   "scam hota hai. Zyada vaada kiya gaya return apne aap mein behtar mauka nahi hota.",
                   "बाज़ार से जुड़े निवेश ईमानदारी से रिटर्न की गारंटी नहीं दे सकते। इतना ऊँचा वादा अक्सर बड़ा जोखिम या ठगी होता है।"),
                 "guaranteed_return"),
               E("e_scarce", L("“Only 10 slots”", "“Sirf 10 slots”", "“सिर्फ़ 10 स्लॉट”"),
                 L("A limited number of places, shrinking fast.", "Gine-chune slots, jo tezi se kam ho rahe hain.",
                   "गिनी-चुनी जगहें, जो तेज़ी से घट रही हैं।"), "red_flag",
                 L("Artificial scarcity pushes you to act before you can check facts.",
                   "Banavati kami aapko facts check karne se pehle hi kadam uthane par majboor karti hai.",
                   "बनावटी कमी आपको तथ्य जाँचने से पहले ही कदम उठाने पर मजबूर करती है।"), "scarcity"),
               E("e_urgent", L("“Invest today”", "“Aaj hi invest karo”", "“आज ही निवेश करें”"),
                 L("A same-day deadline.", "Usi din ki deadline.", "उसी दिन की समय-सीमा।"), "red_flag",
                 L("Genuine, regulated products do not need you to decide within minutes. Urgency is a pressure tactic, "
                   "not evidence of a disappearing opportunity.",
                   "Asli, regulated products ke liye aapko minutes mein faisla nahi karna padta. Jaldi ek dabaav ki chaal hai, "
                   "mauka khatam hone ka saboot nahi.",
                   "असली, विनियमित उत्पादों के लिए मिनटों में फ़ैसला नहीं करना पड़ता। जल्दबाज़ी दबाव की चाल है।"), "urgency"),
               E("e_stranger", L("Added by an unknown number", "Anjaan number ne group mein add kiya",
                                 "अनजान नंबर ने ग्रुप में जोड़ा"),
                 L("Rahul never asked to join this group.", "Rahul ne is group mein judne ko nahi kaha tha.",
                   "राहुल ने इस ग्रुप में जुड़ने को नहीं कहा था।"), "red_flag",
                 L("Unsolicited financial offers from strangers are a classic scam entry point.",
                   "Anjaan logon ke bin-bulaye financial offers scam ka aam tareeka hain.",
                   "अजनबियों के बिन-बुलाए वित्तीय प्रस्ताव ठगी का आम तरीका हैं।"), "unsolicited"),
               E("e_group", L("240 members in the group", "Group mein 240 members", "ग्रुप में 240 सदस्य"),
                 L("The group looks busy and popular.", "Group busy aur popular dikhta hai.", "ग्रुप व्यस्त और लोकप्रिय दिखता है।"),
                 "red_flag",
                 L("Group size is not evidence. Members can be bots, paid accounts or strangers who never invested.",
                   "Group ka size saboot nahi hai. Members bots, paid accounts ya aise log ho sakte hain jinhone kabhi invest nahi kiya.",
                   "ग्रुप का आकार सबूत नहीं है। सदस्य बॉट या पेड अकाउंट हो सकते हैं।"), "social_proof"),
               E("e_missing", L("No company name, no risks, no fees", "Na company ka naam, na risk, na fees",
                                "न कंपनी का नाम, न जोखिम, न शुल्क"),
                 L("The message never says who runs the scheme, what the risks are or what it costs.",
                   "Message mein kahin nahi likha ki scheme kaun chalata hai, risk kya hain ya kharcha kya hai.",
                   "संदेश में नहीं बताया कि स्कीम कौन चलाता है, जोखिम क्या हैं या खर्च क्या है।"), "red_flag",
                 L("Genuine offers disclose who is responsible, the risks and the costs. Missing disclosures matter.",
                   "Asli offers batate hain ki zimmedar kaun hai, risk aur kharche kya hain. Gayab jaankari bhi ek signal hai.",
                   "असली प्रस्ताव बताते हैं कि जिम्मेदार कौन है, जोखिम और खर्च क्या हैं। गायब जानकारी भी संकेत है।"),
                 "missing_disclosure"),
               E("e_tone", L("Polished, friendly message with a logo", "Polished, dostana message, logo ke saath",
                             "सजा-संवरा, दोस्ताना संदेश, लोगो के साथ"),
                 L("It looks professional.", "Professional dikhta hai.", "यह पेशेवर दिखता है।"), "reassuring",
                 L("Good design is cheap to copy. Looking professional is not evidence of being genuine.",
                   "Achha design copy karna sasta hai. Professional dikhna asli hone ka saboot nahi.",
                   "अच्छा डिज़ाइन नक़ल करना आसान है। पेशेवर दिखना असली होने का सबूत नहीं।"))],
           actions=[
               A("invest", L("Invest now — I don't want to miss this", "Abhi invest karo — mauka haath se nahi jaane dena",
                             "अभी निवेश करो — मौका हाथ से नहीं जाने देना"), "unsafe", "s2_fee",
                 L("You send a simulated ₹5,000. A dashboard instantly shows ₹6,500 'profit'. Then a new message arrives…",
                   "Aap simulated ₹5,000 bhejte ho. Dashboard turant ₹6,500 'profit' dikhata hai. Phir ek naya message aata hai…",
                   "आप सिम्युलेटेड ₹5,000 भेजते हैं। डैशबोर्ड तुरंत ₹6,500 'मुनाफ़ा' दिखाता है। फिर नया संदेश आता है…"),
                 simple=L("Invest now", "Abhi invest karo", "अभी निवेश करें"), verification=False,
                 misconception_signals=["M001", "M006"]),
               A("verify", L("Ask the sender to prove he is registered", "Bhejne wale se registration ka saboot maango",
                             "भेजने वाले से पंजीकरण का सबूत माँगें"), "mixed", "s3_regclaim",
                 L("He replies within seconds with a registration number and a certificate image.",
                   "Wo kuch hi seconds mein registration number aur certificate ki image bhej deta hai.",
                   "वह कुछ ही सेकंड में पंजीकरण नंबर और प्रमाणपत्र की तस्वीर भेज देता है।"),
                 simple=L("Ask for proof", "Saboot maango", "सबूत माँगें"), requests_evidence=True),
               A("investigate", L("Put the phone down and look into it myself", "Phone rakho aur khud jaanch-padtaal karo",
                                  "फ़ोन रखें और खुद जाँच-पड़ताल करें"), "safe", "s6_investigation",
                 L("You step away from the pressure and begin checking independently.",
                   "Aap dabaav se door hokar khud se check karna shuru karte ho.",
                   "आप दबाव से दूर होकर खुद जाँच शुरू करते हैं।"),
                 simple=L("Check it myself", "Khud check karo", "खुद जाँचें"), verification=True, requests_evidence=True),
               A("questions", L("Ask a few questions in the group", "Group mein kuch sawaal poochho",
                                "ग्रुप में कुछ सवाल पूछें"), "mixed", "s4_pressure",
                 L("Your questions get quick, smooth answers — and other members start replying “I'm already in!”",
                   "Aapke sawaalon ke jawab turant, chikne-chupde milte hain — aur doosre members likhne lagte hain “Main to pehle se hoon!”",
                   "आपके सवालों के तुरंत, चिकने-चुपड़े जवाब मिलते हैं — और दूसरे सदस्य लिखने लगते हैं “मैं तो पहले से हूँ!”"),
                 simple=L("Ask questions", "Sawaal poochho", "सवाल पूछें"), requests_evidence=True),
               A("walk", L("Ignore it and leave the group", "Ignore karo aur group chhod do", "अनदेखा करें और ग्रुप छोड़ दें"),
                 "safe", "t_walk",
                 L("You mute the chat and leave the group.", "Aap chat mute karke group chhod dete ho.",
                   "आप चैट म्यूट करके ग्रुप छोड़ देते हैं।"),
                 simple=L("Walk away", "Door ho jao", "दूर हो जाएँ"))],
           reasoning_prompt=L("In your own words: what is going through your mind?",
                              "Apne shabdon mein likho: aapke dimaag mein kya chal raha hai?",
                              "अपने शब्दों में लिखें: आपके मन में क्या चल रहा है?")),

        ST("s2_fee", L("The withdrawal wall", "Withdrawal ki deewar", "निकासी की दीवार"),
           L("The dashboard shows ₹6,500 next to your name. When you try to withdraw, a new rule appears.",
             "Dashboard mein aapke naam ke aage ₹6,500 dikhta hai. Jab aap nikalne ki koshish karte ho, ek naya niyam aa jaata hai.",
             "डैशबोर्ड में आपके नाम के आगे ₹6,500 दिखता है। निकालने की कोशिश पर एक नया नियम आ जाता है।"),
           channel=CH("app", "WealthWave Portal (fictional)", [
               L("Withdrawal locked.", "Withdrawal locked hai.", "निकासी बंद है।"),
               L("₹2,000 verification fee required before withdrawal.", "Withdrawal se pehle ₹2,000 verification fee zaroori hai.",
                 "निकासी से पहले ₹2,000 सत्यापन शुल्क ज़रूरी है।"),
               L("Pay within 30 minutes or your profit expires.", "30 minute mein pay karo warna profit expire ho jayega.",
                 "30 मिनट में भुगतान करें वरना मुनाफ़ा समाप्त हो जाएगा।")]),
           pressure=[
               P("loss_recovery", L("You have already put in ₹5,000. Paying ₹2,000 more might get it back.",
                                    "Aap ₹5,000 daal chuke ho. ₹2,000 aur dene se shayad wapas mil jaye.",
                                    "आप ₹5,000 डाल चुके हैं। ₹2,000 और देने से शायद वापस मिल जाए।"), intensity=3),
               P("countdown", L("Pay within 30 minutes (timer compressed for the simulation).",
                                "30 minute mein pay karo (simulation ke liye timer chhota kiya gaya hai).",
                                "30 मिनट में भुगतान करें (सिमुलेशन के लिए टाइमर छोटा)।"), countdown=40)],
           evidence=[
               E("f_fee", L("A fee before you can withdraw", "Withdraw karne se pehle fee", "निकासी से पहले शुल्क"),
                 L("Money out requires more money in.", "Paisa nikalne ke liye aur paisa dena.", "पैसा निकालने के लिए और पैसा देना।"),
                 "red_flag", L("Genuine platforms deduct disclosed charges from your balance; they do not demand new payments "
                               "to release your own money.",
                               "Asli platforms disclosed charges aapke balance se kaatte hain; apna hi paisa nikalne ke liye naya payment nahi maangte.",
                               "असली प्लेटफ़ॉर्म घोषित शुल्क आपके बैलेंस से काटते हैं; अपना पैसा निकालने के लिए नया भुगतान नहीं माँगते।"),
                 "advance_fee"),
               E("f_dash", L("The “profit” is only a number on their screen", "“Profit” sirf unki screen par ek number hai",
                             "“मुनाफ़ा” सिर्फ़ उनकी स्क्रीन पर एक संख्या है"),
                 L("A screen they control shows ₹6,500.", "Unke control wali screen ₹6,500 dikhati hai.", "उनके नियंत्रण वाली स्क्रीन ₹6,500 दिखाती है।"),
                 "red_flag", L("A number on a screen is not money you can access. Scammers use fake dashboards to create trust.",
                               "Screen par number wo paisa nahi jo aap nikal sako. Scammers bharosa banane ke liye nakli dashboard dikhate hain.",
                               "स्क्रीन की संख्या वह पैसा नहीं जिसे आप निकाल सकें। ठग भरोसा बनाने के लिए नकली डैशबोर्ड दिखाते हैं।"),
                 "fake_dashboard"),
               E("f_expire", L("“Profit expires” if you do not pay fast", "Jaldi pay nahi kiya to “profit expire”",
                               "जल्दी भुगतान नहीं किया तो “मुनाफ़ा समाप्त”"),
                 L("A new deadline, tied to your fear of losing what you have.", "Ek nayi deadline, jo kuch kho dene ke darr se judi hai.",
                   "एक नई समय-सीमा, जो खोने के डर से जुड़ी है।"), "red_flag",
                 L("Fear and urgency stop you from thinking. The pressure itself is the warning sign.",
                   "Darr aur jaldi aapko sochne nahi deti. Dabaav hi khatre ki nishani hai.",
                   "डर और जल्दबाज़ी सोचने नहीं देती। दबाव ही चेतावनी है।"), "fear"),
               E("f_win", L("Members post “withdrawal successful” screenshots", "Members “withdrawal successful” ke screenshots daalte hain",
                            "सदस्य “निकासी सफल” के स्क्रीनशॉट डालते हैं"),
                 L("Screenshots from accounts you cannot verify.", "Aise accounts ke screenshots jinhe aap verify nahi kar sakte.",
                   "ऐसे खातों के स्क्रीनशॉट जिन्हें आप जाँच नहीं सकते।"), "red_flag",
                 L("Screenshots are easy to fake and posters may be part of the scheme.",
                   "Screenshots nakli banana aasan hai aur post karne wale scheme ka hissa ho sakte hain.",
                   "स्क्रीनशॉट नकली बनाना आसान है और पोस्ट करने वाले स्कीम का हिस्सा हो सकते हैं।"), "social_proof")],
           actions=[
               A("pay_fee", L("Pay ₹2,000 — I've come this far", "₹2,000 pay karo — itna aage aa chuka hoon",
                              "₹2,000 भरें — इतना आगे आ चुका हूँ"), "unsafe", "s7_spiral",
                 L("You pay. The portal says “Verification complete” — and a new message appears.",
                   "Aap pay karte ho. Portal likhta hai “Verification complete” — aur ek naya message aata hai.",
                   "आप भुगतान करते हैं। पोर्टल लिखता है “सत्यापन पूरा” — और नया संदेश आता है।"),
                 simple=L("Pay the fee", "Fee bharo", "शुल्क भरें"), verification=False, misconception_signals=["M010"]),
               A("verify_now", L("Stop and check whether this company really exists", "Ruko aur check karo ki ye company sach mein hai ya nahi",
                                 "रुकें और जाँचें कि यह कंपनी सच में है या नहीं"), "safe", "s6_investigation",
                 L("You stop paying and start checking independently.", "Aap paisa dena rok kar khud se check karte ho.",
                   "आप भुगतान रोककर खुद जाँच शुरू करते हैं।"),
                 simple=L("Stop and check", "Ruko aur check karo", "रुकें और जाँचें"), verification=True, requests_evidence=True),
               A("stop_pay", L("Stop paying and cut contact", "Pay karna band karo aur sampark todo",
                               "भुगतान बंद करें और संपर्क तोड़ें"), "safe", "t_stopped_loss",
                 L("You block the sender. The ₹5,000 is gone, but you stop it there.",
                   "Aap sender ko block karte ho. ₹5,000 gaye, par aap yahin rok dete ho.",
                   "आप भेजने वाले को ब्लॉक करते हैं। ₹5,000 गए, पर आप वहीं रोक देते हैं।"),
                 simple=L("Stop and block", "Ruko aur block karo", "रुकें और ब्लॉक करें")),
               A("refund", L("Ask the admin to refund my ₹5,000 first", "Pehle admin se ₹5,000 refund maango",
                             "पहले एडमिन से ₹5,000 वापस माँगें"), "mixed", "s7_spiral",
                 L("The admin says refunds are processed after the verification fee. More pressure follows.",
                   "Admin kehta hai refund verification fee ke baad hota hai. Dabaav aur badhta hai.",
                   "एडमिन कहता है रिफ़ंड सत्यापन शुल्क के बाद होता है। दबाव और बढ़ता है।"),
                 requests_evidence=True, misconception_signals=["M010"])],
           reasoning_prompt=L("What made you choose this?", "Ye kyun chuna?", "यह क्यों चुना?")),

        ST("s7_spiral", L("One more step", "Bas ek aur kadam", "बस एक और कदम"),
           L("After the fee, a new charge appears. You have now paid ₹7,000 in simulated money.",
             "Fee ke baad ek naya charge aa jaata hai. Ab tak aap simulated ₹7,000 de chuke ho.",
             "शुल्क के बाद नया चार्ज आ जाता है। अब तक आप सिम्युलेटेड ₹7,000 दे चुके हैं।"),
           channel=CH("app", "WealthWave Portal (fictional)", [
               L("Verification complete.", "Verification complete.", "सत्यापन पूरा।"),
               L("Tax clearance of ₹8,500 is required to release ₹6,500.", "₹6,500 release karne ke liye ₹8,500 tax clearance chahiye.",
                 "₹6,500 निकालने के लिए ₹8,500 टैक्स क्लियरेंस चाहिए।"),
               L("Last step. Pay now or the account freezes.", "Aakhri step. Abhi pay karo warna account freeze.",
                 "आख़िरी कदम। अभी भुगतान करें वरना अकाउंट फ़्रीज़।")]),
           pressure=[P("loss_recovery", L("You've already paid ₹7,000. Only ₹8,500 more…", "Aap ₹7,000 de chuke ho. Bas ₹8,500 aur…",
                                          "आप ₹7,000 दे चुके हैं। बस ₹8,500 और…"), intensity=3),
                     P("fear", L("The account will freeze.", "Account freeze ho jayega.", "अकाउंट फ़्रीज़ हो जाएगा।"))],
           evidence=[
               E("sp_new", L("A new fee after you paid the first one", "Pehli fee ke baad ek nayi fee", "पहले शुल्क के बाद नया शुल्क"),
                 L("Each payment is followed by a new reason to pay.", "Har payment ke baad pay karne ka naya bahana.",
                   "हर भुगतान के बाद भुगतान का नया बहाना।"), "red_flag",
                 L("Scams escalate. Each payment makes you feel you've invested too much to stop — that feeling is the trap.",
                   "Scams badhte jaate hain. Har payment ke baad lagta hai ab rukna nuksaan hoga — wahi ehsaas jaal hai.",
                   "ठगी बढ़ती जाती है। हर भुगतान के बाद रुकना नुकसान लगता है — वही एहसास जाल है।"), "advance_fee"),
               E("sp_tax", L("“Tax clearance” demanded as a transfer", "“Tax clearance” transfer ke roop mein maanga gaya",
                             "“टैक्स क्लियरेंस” ट्रांसफ़र के रूप में माँगा गया"),
                 L("A stranger asks you to pay a tax directly to an individual's account.", "Anjaan aadmi tax seedha kisi vyakti ke account mein maangta hai.",
                   "अजनबी टैक्स सीधे किसी व्यक्ति के खाते में माँगता है।"), "red_flag",
                 L("Genuine charges and taxes appear in official documents; they are not collected as ad-hoc transfers to a personal account.",
                   "Asli charges aur taxes official documents mein dikhte hain; personal account mein adhoc transfer se nahi liye jaate.",
                   "असली शुल्क और टैक्स आधिकारिक दस्तावेज़ों में दिखते हैं; व्यक्तिगत खाते में अलग से नहीं लिए जाते।"), "fake_charge"),
               E("sp_sunk", L("The money already paid is gone either way", "Jo paisa de diya wo dono taraf gaya hi hai",
                              "जो पैसा दे दिया वह दोनों तरफ़ गया ही है"),
                 L("Paying more does not bring back what was paid.", "Aur dene se pehle diya hua paisa wapas nahi aata.",
                   "और देने से पहले दिया पैसा वापस नहीं आता।"), "neutral",
                 L("This is the sunk-cost trap: past payments are not a reason to make a new one.", "Ye sunk-cost ka jaal hai: pichhle payments naye payment ki wajah nahi.",
                   "यह सनक-कॉस्ट का जाल है: पिछले भुगतान नए भुगतान का कारण नहीं।"))],
           actions=[
               A("pay_again", L("Pay ₹8,500 — I can't lose it all", "₹8,500 bharo — sab kuch nahi kho sakta",
                                "₹8,500 भरें — सब कुछ नहीं खो सकता"), "unsafe", "t_deep_loss",
                 L("You pay. The portal asks for another “insurance fee”.", "Aap pay karte ho. Portal ek aur “insurance fee” maangta hai.",
                   "आप भुगतान करते हैं। पोर्टल एक और “बीमा शुल्क” माँगता है।"),
                 simple=L("Pay more", "Aur bharo", "और भरें"), misconception_signals=["M010"]),
               A("stop_report", L("Stop. Save screenshots and report it", "Ruko. Screenshots rakho aur report karo",
                                  "रुकें। स्क्रीनशॉट रखें और रिपोर्ट करें"), "safe", "t_stopped_late",
                 L("You stop paying, save the evidence and report it (in India: the national cyber-crime helpline 1930 or cybercrime.gov.in).",
                   "Aap paisa dena rokte ho, saboot rakhte ho aur report karte ho (India mein: national cyber-crime helpline 1930 ya cybercrime.gov.in).",
                   "आप भुगतान रोकते हैं, सबूत रखते हैं और रिपोर्ट करते हैं (भारत में: राष्ट्रीय साइबर-अपराध हेल्पलाइन 1930 या cybercrime.gov.in)।"),
                 simple=L("Stop and report", "Ruko aur report karo", "रुकें और रिपोर्ट करें"), verification=True)],
           reasoning_prompt=L("What are you weighing right now?", "Abhi aap kya tol rahe ho?", "अभी आप क्या तौल रहे हैं?")),

        ST("s3_regclaim", L("A certificate arrives", "Ek certificate aata hai", "प्रमाणपत्र आता है"),
           L("Aarav replies instantly with a registration number and a certificate image.",
             "Aarav turant registration number aur certificate ki image ke saath jawab deta hai.",
             "आरव तुरंत पंजीकरण नंबर और प्रमाणपत्र की तस्वीर के साथ जवाब देता है।"),
           channel=CH("telegram", "Aarav Mehta · WealthWave Circle (fictional)", [
               L("Here is our SEBI registration: INZ000-FICTIONAL-0421.", "Ye hamara SEBI registration hai: INZ000-FICTIONAL-0421.",
                 "यह हमारा SEBI पंजीकरण है: INZ000-FICTIONAL-0421।"),
               L("[certificate image]", "[certificate ki image]", "[प्रमाणपत्र की तस्वीर]"),
               L("We are 100% genuine. Slots are filling — decide in the next few minutes!", "Hum 100% asli hain. Slots bhar rahe hain — agle kuch minutes mein faisla karo!",
                 "हम 100% असली हैं। स्लॉट भर रहे हैं — अगले कुछ मिनटों में फ़ैसला करें!")]),
           pressure=[P("authority", L("An official-looking certificate.", "Official dikhne wala certificate.", "आधिकारिक दिखने वाला प्रमाणपत्र।")),
                     P("countdown", L("Decide in the next few minutes!", "Agle kuch minutes mein faisla karo!", "अगले कुछ मिनटों में फ़ैसला करें!"), countdown=40)],
           evidence=[
               E("r_num", L("The number was supplied by the sender", "Number bhejne wale ne khud diya", "नंबर भेजने वाले ने खुद दिया"),
                 L("Nothing proves the number is real or belongs to him.", "Kuch bhi saabit nahi karta ki number asli hai ya uska hai.",
                   "कुछ भी साबित नहीं करता कि नंबर असली है या उसका है।"), "red_flag",
                 L("Anyone can type a number. It only counts if you look it up yourself on the regulator's official website, typed in manually — not via a link he sends.",
                   "Number koi bhi likh sakta hai. Wo tabhi maayne rakhta hai jab aap khud regulator ki official website par check karo — uske bheje link se nahi.",
                   "नंबर कोई भी लिख सकता है। वह तभी मायने रखता है जब आप खुद नियामक की वेबसाइट पर जाँचें — उसके भेजे लिंक से नहीं।"), "authority_claim"),
               E("r_img", L("A certificate image, not a checkable record", "Certificate ki image, jaanchne layak record nahi",
                            "प्रमाणपत्र की तस्वीर, जाँचने योग्य रिकॉर्ड नहीं"),
                 L("Images are easy to edit.", "Images edit karna aasan hai.", "तस्वीरें एडिट करना आसान है।"), "red_flag",
                 L("A picture can be edited in minutes; a registry lookup cannot.", "Image minutes mein edit ho sakti hai; registry lookup nahi.",
                   "तस्वीर मिनटों में एडिट हो सकती है; रजिस्ट्री खोज नहीं।"), "forged_document"),
               E("r_name", L("The certificate name differs from the group name", "Certificate ka naam group ke naam se alag hai",
                             "प्रमाणपत्र का नाम ग्रुप के नाम से अलग"),
                 L("The group says WealthWave; the certificate names a different entity.", "Group WealthWave kehta hai; certificate mein alag entity ka naam hai.",
                   "ग्रुप WealthWave कहता है; प्रमाणपत्र में अलग संस्था का नाम है।"), "red_flag",
                 L("Inconsistent names are a basic mismatch you can spot without any special knowledge.", "Naam ka mel na khana aisi baat hai jo bina khaas jaankari ke pakdi ja sakti hai.",
                   "नामों का मेल न खाना ऐसी बात है जो बिना विशेष ज्ञान के पकड़ी जा सकती है।"), "inconsistent_info"),
               E("r_pay", L("Payment goes to a personal account", "Payment ek personal account mein jaata hai", "भुगतान व्यक्तिगत खाते में जाता है"),
                 L("The collection account belongs to an individual, not a company.", "Collection account kisi vyakti ka hai, company ka nahi.",
                   "कलेक्शन खाता किसी व्यक्ति का है, कंपनी का नहीं।"), "red_flag",
                 L("Registered firms collect through accounts in the firm's name with proper receipts.", "Registered firms apne naam ke account mein receipt ke saath paisa leti hain.",
                   "पंजीकृत फर्में अपने नाम के खाते में रसीद के साथ पैसा लेती हैं।"), "personal_account"),
               E("r_call", L("He avoids a video call or a meeting", "Wo video call ya milne se bachta hai", "वह वीडियो कॉल या मुलाक़ात से बचता है"),
                 L("He only wants to chat.", "Wo sirf chat karna chahta hai.", "वह सिर्फ़ चैट करना चाहता है।"), "red_flag",
                 L("Avoiding accountability is a warning sign.", "Jawabdehi se bachna chetavani ka sanket hai.", "जवाबदेही से बचना चेतावनी का संकेत है।"), "avoids_accountability")],
           actions=[
               A("check_independent", L("Check the number myself on the regulator's official website", "Number ko regulator ki official website par khud check karo",
                                        "नंबर को नियामक की आधिकारिक वेबसाइट पर खुद जाँचें"), "safe", "s6_investigation",
                 L("You type the official website address yourself and search. Let's see what turns up…", "Aap official website ka address khud type karke search karte ho. Dekhte hain kya milta hai…",
                   "आप आधिकारिक वेबसाइट का पता खुद टाइप करके खोजते हैं। देखते हैं क्या मिलता है…"),
                 simple=L("Check it myself", "Khud check karo", "खुद जाँचें"), verification=True, requests_evidence=True),
               A("accept", L("That looks official — I'll invest", "Ye official lagta hai — main invest karta hoon",
                             "यह आधिकारिक लगता है — मैं निवेश करता हूँ"), "unsafe", "s2_fee",
                 L("You send a simulated ₹5,000 to the account he gives you.", "Aap uske diye account mein simulated ₹5,000 bhejte ho.",
                   "आप उसके दिए खाते में सिम्युलेटेड ₹5,000 भेजते हैं।"),
                 simple=L("Trust it and invest", "Bharosa karke invest", "भरोसा करके निवेश"), verification=False, misconception_signals=["M007"]),
               A("more_proof", L("Ask for a video call and a company address", "Video call aur company ka address maango",
                                 "वीडियो कॉल और कंपनी का पता माँगें"), "mixed", "s4_pressure",
                 L("He dodges: “We are busy. Slots are almost over.” Then a friend of yours messages…",
                   "Wo taal deta hai: “Hum busy hain. Slots lagbhag khatam.” Phir aapka ek dost message karta hai…",
                   "वह टाल देता है: “हम व्यस्त हैं। स्लॉट लगभग ख़त्म।” फिर आपका एक दोस्त संदेश करता है…"),
                 simple=L("Ask for a call", "Call maango", "कॉल माँगें"), requests_evidence=True)],
           reasoning_prompt=L("How do you decide whether this certificate is real?", "Aap kaise tay karoge ki ye certificate asli hai?",
                              "आप कैसे तय करेंगे कि यह प्रमाणपत्र असली है?")),

        ST("s4_pressure", L("A friend joins the push", "Ek dost bhi dabaav mein shamil", "दोस्त भी दबाव में शामिल"),
           L("Neha, a college friend who is also in the group, messages you privately.",
             "Neha, college ki ek dost jo group mein hai, aapko private message karti hai.",
             "नेहा, कॉलेज की एक दोस्त जो ग्रुप में है, आपको निजी संदेश भेजती है।"),
           channel=CH("chat", "Neha (friend, fictional)", [
               L("I put in ₹10,000 yesterday. He's legit — I saw a withdrawal!", "Maine kal ₹10,000 lagaye. Wo sahi hai — maine withdrawal dekha!",
                 "मैंने कल ₹10,000 लगाए। वह सही है — मैंने निकासी देखी!"),
               L("Join before slots end, don't be silly.", "Slots khatam hone se pehle judo, bevakoof mat bano.",
                 "स्लॉट ख़त्म होने से पहले जुड़ो, बेवक़ूफ़ मत बनो।")]),
           pressure=[P("social_proof", L("“Everyone I know is in.”", "“Mere jaan-pehchan wale sab ismein hain.”", "“मेरे जान-पहचान वाले सब इसमें हैं।”"), intensity=3),
                     P("peer_pressure", L("Your friend is urging you.", "Aapki dost aapko kehti hai.", "आपकी दोस्त आपको कह रही है।")),
                     P("scarcity", L("Only 3 slots left.", "Sirf 3 slots bache.", "सिर्फ़ 3 स्लॉट बचे।"), countdown=30)],
           evidence=[
               E("n_exp", L("Neha's experience is one person's claim", "Neha ka anubhav ek vyakti ka daava hai", "नेहा का अनुभव एक व्यक्ति का दावा है"),
                 L("She says she saw a withdrawal.", "Wo kehti hai usne withdrawal dekha.", "वह कहती है उसने निकासी देखी।"), "red_flag",
                 L("A sincere friend can still be fooled — she may have seen the same kind of fake dashboard. A friend's recommendation is not independent evidence.",
                   "Sachchi dost bhi dhokha kha sakti hai — usne bhi wahi nakli dashboard dekha hoga. Dost ki salah swatantra saboot nahi hai.",
                   "सच्ची दोस्त भी धोखा खा सकती है — उसने भी वैसा ही नकली डैशबोर्ड देखा होगा। दोस्त की सलाह स्वतंत्र सबूत नहीं है।"), "friend_claim"),
               E("n_slots", L("Slots fell from 10 to 3 in minutes", "Slots minutes mein 10 se 3 ho gaye", "स्लॉट मिनटों में 10 से 3 हुए"),
                 L("The numbers shrink as you hesitate.", "Aap jitna hichkichate ho, number utna ghat'ta hai.", "आप जितना हिचकिचाते हैं, संख्या उतनी घटती है।"), "red_flag",
                 L("Scarcity that changes when you hesitate is a script, not a fact.", "Jo kami aapke hichkichane par badle wo script hai, tathya nahi.",
                   "जो कमी आपके हिचकिचाने पर बदले वह स्क्रिप्ट है, तथ्य नहीं।"), "scarcity"),
               E("n_bonus", L("Neha mentions a referral bonus", "Neha referral bonus ka zikr karti hai", "नेहा रेफ़रल बोनस का ज़िक्र करती है"),
                 L("She earns a bonus when she brings friends in.", "Dost laane par use bonus milta hai.", "दोस्त लाने पर उसे बोनस मिलता है।"), "red_flag",
                 L("When someone is paid for bringing you in, they have a reason to push — even if they are honest.",
                   "Jab kisi ko aapko laane ke paise milte hain, uske paas dabaav daalne ki wajah hoti hai — chaahe wo imaandaar ho.",
                   "जब किसी को आपको लाने के पैसे मिलते हैं, उसके पास दबाव डालने की वजह होती है।"), "conflict_of_interest")],
           actions=[
               A("follow_friend", L("Neha is a friend — if she's in, it's probably fine", "Neha dost hai — wo ismein hai to theek hi hoga",
                                    "नेहा दोस्त है — वह इसमें है तो ठीक ही होगा"), "unsafe", "s2_fee",
                 L("You invest a simulated ₹5,000. Then the withdrawal wall appears.", "Aap simulated ₹5,000 lagate ho. Phir withdrawal ki deewar aa jaati hai.",
                   "आप सिम्युलेटेड ₹5,000 लगाते हैं। फिर निकासी की दीवार आ जाती है।"),
                 simple=L("Follow my friend", "Dost ke saath jao", "दोस्त के साथ जाएँ"), verification=False, misconception_signals=["M002", "M011"]),
               A("hold_verify", L("I'll check it myself first, even if I miss the slot", "Pehle khud check karunga, chaahe slot chhoot jaye",
                                  "पहले खुद जाँचूँगा, भले स्लॉट छूट जाए"), "safe", "s6_investigation",
                 L("You tell Neha you will check first. You begin investigating.", "Aap Neha ko kehte ho ki pehle check karoge. Aap jaanch shuru karte ho.",
                   "आप नेहा से कहते हैं कि पहले जाँचेंगे। आप जाँच शुरू करते हैं।"),
                 simple=L("Check first", "Pehle check karo", "पहले जाँचें"), verification=True, requests_evidence=True),
               A("warn_friend", L("Ask Neha to pause and check before adding more money", "Neha se kaho ruke aur aur paisa daalne se pehle check kare",
                                  "नेहा से कहें रुके और और पैसा डालने से पहले जाँचे"), "safe", "t_helped_friend",
                 L("You share how to check registration independently. Neha agrees to pause.", "Aap batate ho registration khud kaise check karte hain. Neha ruk jaati hai.",
                   "आप बताते हैं कि पंजीकरण खुद कैसे जाँचें। नेहा रुक जाती है।"),
                 simple=L("Warn Neha", "Neha ko aagah karo", "नेहा को आगाह करें"), verification=True)],
           reasoning_prompt=L("How much does Neha's message change what you believe — and why?", "Neha ke message se aapka vishwas kitna badla — aur kyun?",
                              "नेहा के संदेश से आपका विश्वास कितना बदला — और क्यों?")),

        ST("s6_investigation", L("What the checks show", "Jaanch mein kya mila", "जाँच में क्या मिला"),
           L("You take 20 calm minutes and look up the claims yourself. These are the (fictional) findings.",
             "Aap 20 shaant minute lekar daavon ko khud check karte ho. Ye (kaalpanik) nateeje hain.",
             "आप 20 शांत मिनट लेकर दावों की खुद जाँच करते हैं। ये (काल्पनिक) नतीजे हैं।"),
           channel=CH("document", "Your notes", [
               L("Findings from independent checks", "Swatantra jaanch ke nateeje", "स्वतंत्र जाँच के नतीजे")]),
           evidence=[
               E("i_dir", L("The company is not in the regulator's list of registered intermediaries", "Company regulator ki registered intermediaries ki list mein nahi hai",
                            "कंपनी नियामक की पंजीकृत मध्यस्थों की सूची में नहीं है"),
                 L("A search of the official directory returns nothing for this name.", "Official directory mein is naam ka kuch nahi milta.",
                   "आधिकारिक निर्देशिका में इस नाम का कुछ नहीं मिलता।"), "red_flag",
                 L("The one check that matters most: the claimed registration does not exist in the official record.", "Sabse zaroori check: daava kiya gaya registration official record mein hai hi nahi.",
                   "सबसे ज़रूरी जाँच: दावा किया गया पंजीकरण आधिकारिक रिकॉर्ड में है ही नहीं।"), "no_registration"),
               E("i_guar", L("“Guaranteed 30%” contradicts how market-linked returns work", "“Guaranteed 30%” market-linked returns ke tareeke ke ulat hai",
                             "“गारंटीशुदा 30%” बाज़ार-आधारित रिटर्न की प्रकृति के उलट है"),
                 L("Genuine education material says returns on market-linked products vary and are not guaranteed.", "Asli shiksha-samagri kehti hai market-linked products ke returns badalte hain aur guarantee nahi hote.",
                   "असली शिक्षण सामग्री कहती है कि बाज़ार-आधारित उत्पादों के रिटर्न बदलते हैं और गारंटीशुदा नहीं होते।"), "red_flag",
                 L("The central promise cannot be true as stated.", "Mukhya vaada jaisa likha hai waisa sach nahi ho sakta.", "मुख्य वादा जैसा लिखा है वैसा सच नहीं हो सकता।"), "guaranteed_return"),
               E("i_acct", L("The payment account belongs to an individual", "Payment account kisi vyakti ka hai", "भुगतान खाता किसी व्यक्ति का है"),
                 L("The named account holder is a person, not the company.", "Account holder ek vyakti hai, company nahi.", "खाताधारक एक व्यक्ति है, कंपनी नहीं।"), "red_flag",
                 L("Money should go to a company account that matches the company named.", "Paisa company ke naam wale account mein jaana chahiye.",
                   "पैसा कंपनी के नाम वाले खाते में जाना चाहिए।"), "personal_account"),
               E("i_del", L("The admin deletes members' questions about withdrawals", "Admin withdrawals ke baare mein poochhe sawaal delete karta hai",
                            "एडमिन निकासी के बारे में पूछे सवाल हटा देता है"),
                 L("Questions disappear; only success stories stay.", "Sawaal gayab, sirf success stories rehti hain.", "सवाल ग़ायब, सिर्फ़ सफलता की कहानियाँ रहती हैं।"), "red_flag",
                 L("Suppressing questions hides problems.", "Sawaal dabaana samasyaayein chhupaata hai.", "सवाल दबाना समस्याएँ छिपाता है।"), "suppressed_questions"),
               E("i_age", L("The group and website are three weeks old", "Group aur website teen hafte purane hain", "ग्रुप और वेबसाइट तीन हफ़्ते पुराने हैं"),
                 L("No track record exists.", "Koi track record nahi hai.", "कोई ट्रैक रिकॉर्ड नहीं है।"), "red_flag",
                 L("A brand-new presence making big claims has nothing behind it to verify.", "Bilkul nayi maujoodgi jo bade daave karti hai, uske peeche check karne layak kuch nahi.",
                   "बिल्कुल नई मौजूदगी जो बड़े दावे करती है, उसके पीछे जाँचने लायक कुछ नहीं।"), "no_track_record"),
               E("i_none", L("No filings, audited statements or news found", "Koi filings, audited statements ya khabar nahi mili",
                             "कोई फ़ाइलिंग, ऑडिटेड विवरण या ख़बर नहीं मिली"),
                 L("Nothing independent exists to back up the claims.", "Daavon ko sahi thehrane wala koi swatantra saboot nahi.",
                   "दावों का समर्थन करने वाला कोई स्वतंत्र सबूत नहीं।"), "red_flag",
                 L("Absence of independent evidence is itself information.", "Swatantra saboot ka na hona bhi ek jaankari hai.", "स्वतंत्र सबूत का न होना भी जानकारी है।"), "missing_disclosure")],
           actions=[
               A("report_leave", L("Leave, keep screenshots and report the group", "Group chhodo, screenshots rakho aur report karo",
                                   "ग्रुप छोड़ें, स्क्रीनशॉट रखें और रिपोर्ट करें"), "safe", "t_safe_end",
                 L("You leave with your evidence saved and report the group.", "Aap saboot rakhkar group chhodte ho aur report karte ho.",
                   "आप सबूत रखकर ग्रुप छोड़ते हैं और रिपोर्ट करते हैं।"),
                 simple=L("Leave and report", "Chhodo aur report karo", "छोड़ें और रिपोर्ट करें"), verification=True),
               A("warn", L("Warn Neha and others with what I found", "Neha aur doosron ko jo mila wo batao", "नेहा और दूसरों को जो मिला वह बताएँ"),
                 "safe", "t_helped_friend",
                 L("You send Neha your notes and how you checked.", "Aap Neha ko apne notes aur check karne ka tareeka bhejte ho.",
                   "आप नेहा को अपने नोट्स और जाँचने का तरीका भेजते हैं।"),
                 simple=L("Warn others", "Doosron ko aagah karo", "दूसरों को आगाह करें"), verification=True),
               A("test_small", L("Try a very small amount, just to test it", "Bas test ke liye bahut chhota amount try karo",
                                 "सिर्फ़ टेस्ट के लिए बहुत छोटी रकम आज़माएँ"), "unsafe", "t_small_loss",
                 L("You send a simulated ₹500. The dashboard shows ₹650 and a small withdrawal succeeds…", "Aap simulated ₹500 bhejte ho. Dashboard ₹650 dikhata hai aur chhota withdrawal ho jaata hai…",
                   "आप सिम्युलेटेड ₹500 भेजते हैं। डैशबोर्ड ₹650 दिखाता है और छोटी निकासी हो जाती है…"),
                 simple=L("Test with a little", "Thoda sa test karo", "थोड़ा टेस्ट करें"), misconception_signals=["M009"]),
               A("watch", L("Stay silent in the group and watch what happens", "Group mein chup rehkar dekho kya hota hai",
                            "ग्रुप में चुप रहकर देखें क्या होता है"), "safe", "t_watch",
                 L("You stay without paying. Weeks later you notice the group vanish.", "Aap bina paisa diye rehte ho. Hafton baad group gayab ho jaata hai.",
                   "आप बिना पैसा दिए रहते हैं। हफ़्तों बाद ग्रुप ग़ायब हो जाता है।"),
                 simple=L("Just watch", "Bas dekho", "बस देखें"))],
           reasoning_prompt=L("Which finding matters most, and what would you verify next?", "Kaun sa nateeja sabse zaroori hai, aur agla kya check karoge?",
                              "कौन-सा नतीजा सबसे ज़रूरी है, और आगे क्या जाँचेंगे?")),

        END("t_walk", "safe", L("You walked away", "Aap door chale gaye", "आप दूर हट गए"),
            L("You protected yourself without having to prove anything first. Walking away from an unsolicited “guaranteed” offer is a strong, valid choice. "
              "Next time you may also want to check it, so you can warn others.",
              "Aapne pehle kuch sabit kiye bina khud ko bacha liya. Bin-bulaye “guaranteed” offer se door jaana ek mazboot, sahi faisla hai. "
              "Agli baar check bhi kar sakte ho taaki doosron ko aagah kar sako.",
              "आपने कुछ साबित किए बिना खुद को बचा लिया। बिन-बुलाए “गारंटीशुदा” प्रस्ताव से दूर हटना एक मज़बूत, सही फ़ैसला है। "
              "अगली बार जाँच भी कर सकते हैं ताकि दूसरों को आगाह कर सकें।")),
        END("t_safe_end", "safe", L("You verified before paying", "Aapne paise dene se pehle verify kiya", "आपने भुगतान से पहले सत्यापन किया"),
            L("You checked the claims independently, found nothing to support them, and kept your money. Verifying through sources you chose yourself is the skill that protects you.",
              "Aapne daavon ko swatantra roop se check kiya, kuch nahi mila, aur paisa bacha liya. Apne chune hue sroton se verify karna wahi hunar hai jo aapko bachata hai.",
              "आपने दावों की स्वतंत्र जाँच की, कुछ नहीं मिला, और पैसा बचा लिया। खुद चुने स्रोतों से सत्यापन ही वह कौशल है जो आपको बचाता है।")),
        END("t_helped_friend", "safe", L("You protected someone else too", "Aapne doosre ko bhi bachaya", "आपने किसी और को भी बचाया"),
            L("You acted on evidence and shared how to check it. Sharing the method — not just the conclusion — helps people verify things for themselves.",
              "Aapne saboot ke aadhar par kaam kiya aur check karne ka tareeka bataya. Sirf nateeja nahi, tareeka batana logon ko khud verify karna sikhata hai.",
              "आपने सबूत के आधार पर काम किया और जाँचने का तरीका बताया। सिर्फ़ नतीजा नहीं, तरीका बताना लोगों को खुद सत्यापन सिखाता है।")),
        END("t_watch", "mixed", L("You stayed out — and watched", "Aap bahar rahe — aur dekhte rahe", "आप बाहर रहे — और देखते रहे"),
            L("You did not pay, which protected your money. Staying in a group like this can still expose you to more messages and pressure. Leaving and reporting is usually safer.",
              "Aapne paisa nahi diya, isse paisa bacha. Aise group mein rehne se aur messages aur dabaav aa sakte hain. Chhodna aur report karna aam taur par zyada surakshit hai.",
              "आपने पैसा नहीं दिया, इससे पैसा बचा। ऐसे ग्रुप में रहने से और संदेश और दबाव आ सकते हैं। छोड़ना और रिपोर्ट करना आमतौर पर अधिक सुरक्षित है।")),
        END("t_stopped_loss", "mixed", L("You stopped — after a loss", "Aap ruke — nuksaan ke baad", "आप रुके — नुकसान के बाद"),
            L("You cut contact and limited the damage to ₹5,000 (simulated). Stopping early is a real skill. The earlier checkpoint — before paying anything — is where verification protects the most.",
              "Aapne sampark todkar nuksaan ₹5,000 (simulated) par rok diya. Jaldi rukna ek asli hunar hai. Sabse zyada suraksha paise dene se pehle verify karne mein hai.",
              "आपने संपर्क तोड़कर नुकसान ₹5,000 (सिम्युलेटेड) पर रोक दिया। जल्दी रुकना सच्चा कौशल है। सबसे ज़्यादा सुरक्षा पैसा देने से पहले सत्यापन में है।"), loss=5000),
        END("t_stopped_late", "mixed", L("You broke the spiral", "Aapne jaal tod diya", "आपने जाल तोड़ दिया"),
            L("You stopped the escalation after ₹7,000 (simulated) and reported it. The “sunk cost” feeling is the hardest to resist, and you did.",
              "Aapne ₹7,000 (simulated) ke baad badhta jaal rok diya aur report kiya. “Sunk cost” ka ehsaas rokna sabse mushkil hai, aur aapne rok diya.",
              "आपने ₹7,000 (सिम्युलेटेड) के बाद बढ़ता जाल रोका और रिपोर्ट किया। “सनक कॉस्ट” का एहसास रोकना सबसे कठिन है, और आपने रोका।"), loss=7000),
        END("t_deep_loss", "unsafe", L("The requests kept coming", "Maangein aati rahin", "माँगें आती रहीं"),
            L("After paying ₹5,000 + ₹2,000 + ₹8,500 (all simulated), the portal asked for yet another fee. Nothing was ever released. "
              "The goal of the scam was never to return your money — each step was designed to make stopping feel like a loss.",
              "₹5,000 + ₹2,000 + ₹8,500 (sab simulated) dene ke baad portal ne ek aur fee maangi. Kuch bhi release nahi hua. "
              "Scam ka maksad paisa lautana tha hi nahi — har kadam aisa banaya gaya tha ki rukna nuksaan lage.",
              "₹5,000 + ₹2,000 + ₹8,500 (सब सिम्युलेटेड) देने के बाद पोर्टल ने एक और शुल्क माँगा। कुछ भी रिलीज़ नहीं हुआ। "
              "ठगी का मक़सद पैसा लौटाना कभी था ही नहीं — हर कदम ऐसा बनाया गया कि रुकना नुकसान लगे।"), loss=15500),
        END("t_small_loss", "unsafe", L("A small test is still a payment", "Chhota test bhi ek payment hai", "छोटा टेस्ट भी भुगतान है"),
            L("The small ₹650 withdrawal worked — which is a common trust-building tactic. Encouraged, you put in ₹20,000 (simulated) and could never withdraw it. "
              "A successful small test does not prove that a scheme is genuine.",
              "₹650 ka chhota withdrawal ho gaya — ye bharosa banane ki aam chaal hai. Hausla badhne par aapne ₹20,000 (simulated) daale aur kabhi nikal nahi paaye. "
              "Chhote test ka safal hona scheme ke asli hone ka saboot nahi.",
              "₹650 की छोटी निकासी हो गई — यह भरोसा बनाने की आम चाल है। हौसला बढ़ने पर आपने ₹20,000 (सिम्युलेटेड) डाले और कभी निकाल नहीं पाए। "
              "छोटे टेस्ट का सफल होना स्कीम के असली होने का सबूत नहीं।"), loss=20000),
    ],
    reflection={
        "key_points": [
            L("A claim of “SEBI registered” is a claim, not proof. Check registration yourself on the regulator's official site, typed in by you.",
              "“SEBI registered” ek daava hai, saboot nahi. Registration khud regulator ki official site par check karo.",
              "“SEBI पंजीकृत” एक दावा है, सबूत नहीं। पंजीकरण खुद नियामक की आधिकारिक साइट पर जाँचें।"),
            L("“Guaranteed” plus a high return is a red flag, not a reason to hurry.",
              "“Guaranteed” aur ooncha return jaldi ki wajah nahi, red flag hai.", "“गारंटीशुदा” और ऊँचा रिटर्न जल्दी की वजह नहीं, चेतावनी है।"),
            L("Urgency, scarcity and “everyone is in” are pressure tactics. They do not make an offer more real.",
              "Jaldi, kami aur “sab ismein hain” dabaav ki chaalein hain. Isse offer asli nahi ho jaata.",
              "जल्दबाज़ी, कमी और “सब इसमें हैं” दबाव की चालें हैं। इनसे प्रस्ताव असली नहीं हो जाता।"),
            L("A friend's recommendation is not independent evidence. Ask: how could this be checked without trusting the person asking me to pay?",
              "Dost ki salah swatantra saboot nahi. Poochho: bina paisa maangne wale par bharosa kiye ise kaise check karun?",
              "दोस्त की सलाह स्वतंत्र सबूत नहीं। पूछें: पैसा माँगने वाले पर भरोसा किए बिना इसे कैसे जाँचूँ?")],
        "questions": [
            L("What would you verify first next time?", "Agli baar sabse pehle kya verify karoge?", "अगली बार सबसे पहले क्या जाँचेंगे?"),
            L("Which pressure tactic affected you most?", "Kaun si dabaav ki chaal ne sabse zyada asar kiya?", "किस दबाव की चाल ने सबसे ज़्यादा असर किया?")],
        "micro_lesson": {"concept_id": "fraud_red_flags",
                         "title": L("The 5-step check: Claim → Source → Authority → Evidence → Verify",
                                    "5-step check: Daava → Source → Authority → Saboot → Verify", "5-चरण जाँच: दावा → स्रोत → अधिकार → सबूत → सत्यापन"),
                         "body": L("1) Claim: what exactly is being promised? 2) Source: who is saying it, and did you ask them? 3) Authority: is the claimed registration checkable? "
                                   "4) Evidence: what independent proof exists? 5) Verify: check through a source you chose yourself. Decide only after step 5.",
                                   "1) Daava: kya vaada hai? 2) Source: kaun keh raha hai, aapne pucha tha? 3) Authority: kya registration check ho sakta hai? "
                                   "4) Saboot: swatantra saboot kya hai? 5) Verify: apne chune source se check karo. Faisla step 5 ke baad.",
                                   "1) दावा: क्या वादा है? 2) स्रोत: कौन कह रहा है? 3) अधिकार: क्या पंजीकरण जाँचा जा सकता है? 4) सबूत: स्वतंत्र प्रमाण क्या है? 5) सत्यापन: अपने चुने स्रोत से जाँचें।")},
    },
)
