from _lib import A, CH, E, END, L, P, ST, scenario

SC = scenario(
    id="whatsapp_expert",
    title=L("The WhatsApp Expert", "The WhatsApp Expert (Forward wala Guru)"),
    tagline=L("A forwarded video promises tips from an 'ex-top fund manager'.", "Ek forward video 'ex-top fund manager' ke tips ka vaada karta hai."),
    character={"name": "Meera", "age": 52, "role": "school teacher in a family WhatsApp group"},
    difficulty=2,
    concept_tags=["social_proof", "verification", "fraud_red_flags", "risk"],
    pressure_tags=["social_proof", "authority", "greed", "loss_recovery"],
    tests=["M002", "M003", "M005", "M007", "M010", "M011"],
    initial="w1_forward",
    dimensions=["herd_resistance", "independent_reasoning", "evidence_verification", "scam_awareness"],
    states=[
        ST("w1_forward", L("A forward from family", "Parivaar se ek forward"),
           L("Meera's cousin forwards a video to the family WhatsApp group. Many relatives react with 👍. All names and numbers are fictional.",
             "Meera ke cousin ne family WhatsApp group mein ek video forward kiya. Kai rishtedaron ne 👍 diya. Sab naam aur number kaalpanik hain."),
           channel=CH("whatsapp", "Rajesh Bhaiya (cousin, fictional) — Forwarded many times", [
               L("Watch this! Karan Sir's FREE webinar. His students made 85% in the last 3 months 🔥", "Dekho! Karan Sir ka FREE webinar. Unke students ne pichhle 3 mahine mein 85% kamaye 🔥"),
               L("[screenshots of 'profits' from 5 students]", "[5 students ke 'profit' ke screenshots]"),
               L("Join his Premium group for ₹3,000 and get daily tips. Sir is an ex-top fund manager!", "₹3,000 mein Premium group join karo aur daily tips pao. Sir ex-top fund manager hain!")]),
           pressure=[P("social_proof", L("Many relatives in the group have reacted with 👍.", "Group ke kai rishtedaron ne 👍 diya hai.")),
                     P("authority", L("“Ex-top fund manager.”", "“Ex-top fund manager.”")),
                     P("greed", L("“85% in 3 months.”", "“3 mahine mein 85%.”"))],
           evidence=[
               E("k_past", L("“85% in the last 3 months”", "“Pichhle 3 mahine mein 85%”"), L("A past result is advertised as the proof.", "Pichhla result hi saboot ki tarah dikhaya gaya hai."), "red_flag",
                 L("Past results — even real ones — do not guarantee future results, and three months says very little. The number may also be selected or edited.", "Pichhle results — asli bhi ho to — aage ki guarantee nahi, aur teen mahine bahut kam hote hain. Number chuna ya edit kiya bhi ho sakta hai."), "past_performance"),
               E("k_screens", L("Screenshots from 5 'students'", "5 'students' ke screenshots"), L("Five profit screenshots, no dates, no names.", "Paanch profit screenshots, na date, na naam."), "red_flag",
                 L("Screenshots are chosen by the seller and are easy to fake. You are seeing winners only.", "Screenshots seller chunta hai aur nakli banana aasan hai. Aap sirf jeetne walon ko dekh rahe ho."), "cherry_picked"),
               E("k_auth", L("“Ex-top fund manager”", "“Ex-top fund manager”"), L("No firm, years or record is given.", "Na firm, na saal, na record bataya gaya."), "red_flag",
                 L("A title without a checkable record is only a claim. Authority language is not evidence.", "Jaanch-yogya record ke bina title sirf daava hai. Authority wali bhasha saboot nahi."), "authority_claim"),
               E("k_sell", L("Tips are sold for ₹3,000", "Tips ₹3,000 mein bechi ja rahi hain"), L("The seller is paid whether or not tips work.", "Tips kaam kare ya na kare, seller ko paisa milta hai."), "red_flag",
                 L("When someone earns from selling tips, their income does not depend on your results.", "Jab koi tips bechkar kamata hai, uski kamai aapke results par nirbhar nahi."), "conflict_of_interest"),
               E("k_risk", L("No mention of losses or risk", "Nuksaan ya risk ka koi zikr nahi"), L("Only gains are shown.", "Sirf munafa dikhaya gaya hai."), "red_flag",
                 L("Honest material talks about what can go wrong. Missing risk talk is a signal.", "Imaandaar jaankari batati hai ki kya galat ho sakta hai. Risk ka zikr na hona ek sanket hai."), "missing_disclosure"),
               E("k_fwd", L("The message has been forwarded many times", "Message kai baar forward hua hai"), L("Nobody knows who made it first.", "Kisi ko nahi pata pehle kisne banaya."), "red_flag",
                 L("A forward can be repeated by many people who never checked it. Repetition is not verification.", "Forward kai log bina check kiye dohra sakte hain. Dohrana verification nahi hai."), "social_proof"),
               E("k_fam", L("It comes from a cousin you trust", "Ye aapke bharosemand cousin se aaya hai"), L("Rajesh is sincere and well-meaning.", "Rajesh imaandaar aur nek niyat wala hai."), "reassuring",
                 L("Sincerity is not the same as being right. A trusted sender can still pass on a scam.", "Imaandaari ka matlab sahi hona nahi. Bharosemand bhejne wala bhi scam aage badha sakta hai."))],
           actions=[
               A("join_premium", L("Join the Premium group — so many in the family are watching", "Premium group join karo — parivaar mein itne log dekh rahe hain"), "unsafe", "w2_tip",
                 L("You pay a simulated ₹3,000. A 'tip of the day' arrives.", "Aap simulated ₹3,000 dete ho. 'Aaj ka tip' aata hai."), verification=False, misconception_signals=["M002", "M003", "M007"]),
               A("ask_cousin", L("Ask Rajesh what happened to him personally", "Rajesh se poochho ki usse khud kya hua"), "mixed", "w_cousin",
                 L("Rajesh replies warmly and with excitement…", "Rajesh garmjoshi se jawab deta hai…"), requests_evidence=True),
               A("check_claims", L("Check the claims independently before replying", "Reply se pehle daavon ko swatantra roop se check karo"), "safe", "w_check",
                 L("You search for the expert's record and the 85% claim.", "Aap expert ke record aur 85% ke daave ko search karte ho."), verification=True, requests_evidence=True),
               A("ignore", L("Don't join; stay out of it", "Join mat karo; door raho"), "safe", "t_ignore",
                 L("You skip the video and stay out of the group.", "Aap video chhod dete ho aur group se door rehte ho.")),
               A("forward", L("Forward it to my other groups — it looks useful", "Ise apne doosre groups mein bhi forward karo — kaam ka lagta hai"), "unsafe", "t_forwarded",
                 L("You forward it to 30 relatives and friends.", "Aap ise 30 rishtedaron aur dostoon ko forward karte ho."), misconception_signals=["M002"])],
           reasoning_prompt=L("Why does this message feel convincing or not?", "Ye message aapko kyun convincing lagta hai ya nahi?")),
        ST("w_cousin", L("Rajesh's story", "Rajesh ki kahani"),
           L("Rajesh answers your question about his own experience.", "Rajesh apne anubhav ke baare mein aapke sawaal ka jawab deta hai."),
           channel=CH("whatsapp", "Rajesh Bhaiya (cousin, fictional)", [
               L("I made ₹4,000 in two weeks!! Also lost ₹2,500 earlier but forgot to mention 😅", "Do hafte mein ₹4,000 kamaye!! Pehle ₹2,500 ka nuksaan bhi hua tha, batana bhool gaya 😅"),
               L("Sir gives me ₹500 for every person who joins, so tell your friends!", "Sir har naye member ke liye mujhe ₹500 dete hain, to apne dostoon ko bolo!")]),
           pressure=[P("peer_pressure", L("Your cousin is warmly encouraging you.", "Aapka cousin pyaar se aapko protsahit kar raha hai."))],
           evidence=[
               E("c_surv", L("The losses came out only after you asked", "Nuksaan tabhi bataya jab aapne poocha"), L("He forgot the loss until prompted.", "Poochhne par hi nuksaan yaad aaya."), "red_flag",
                 L("People tend to share wins and forget losses, so what you hear is a selected story.", "Log jeet batate hain aur haar bhool jaate hain, isliye jo sunte ho wo chuni hui kahani hoti hai."), "survivorship"),
               E("c_ref", L("He earns ₹500 per person he brings", "Wo har laaye hue vyakti par ₹500 kamata hai"), L("A referral bonus ties his income to your joining.", "Referral bonus uski kamai ko aapke judne se jodta hai."), "red_flag",
                 L("A referral payment gives even a sincere person a reason to push.", "Referral ka paisa imaandaar insaan ko bhi dabaav daalne ki wajah deta hai."), "conflict_of_interest"),
               E("c_net", L("His net result is about ₹1,500 — before the ₹3,000 fee", "Uska net result lagbhag ₹1,500 — ₹3,000 fee se pehle"), L("₹4,000 gain − ₹2,500 earlier loss = ₹1,500, and the ₹3,000 joining fee is separate.", "₹4,000 faayda − ₹2,500 purana nuksaan = ₹1,500, aur ₹3,000 joining fee alag hai."), "neutral",
                 L("Looking at the net figure after all costs gives a clearer picture than headline wins.", "Sab kharche ke baad net figure dekhna headline jeet se saaf tasveer deta hai."))],
           actions=[
               A("trust_cousin", L("He's family — he wouldn't mislead me", "Wo apna hai — mujhe gumrah nahi karega"), "unsafe", "w2_tip",
                 L("You join. A tip of the day arrives.", "Aap join karte ho. Aaj ka tip aata hai."), verification=False, misconception_signals=["M011"]),
               A("check_after", L("Thank him, then check the claims independently", "Use shukriya kaho, phir daavon ko swatantra roop se check karo"), "safe", "w_check",
                 L("You begin checking the expert's record.", "Aap expert ka record check karna shuru karte ho."), verification=True, requests_evidence=True),
               A("gently_point", L("Point out the referral bonus and suggest he step back", "Referral bonus ki taraf ishara karo aur use peeche hatne ko kaho"), "safe", "t_helped_family",
                 L("Rajesh is quiet for a moment, then agrees to pause.", "Rajesh thodi der chup rehta hai, phir ruk jaata hai."), verification=True)],
           reasoning_prompt=L("What does Rajesh's reply tell you, and what does it not?", "Rajesh ke jawab se kya pata chalta hai, aur kya nahi?")),
        ST("w2_tip", L("The tip of the day", "Aaj ka tip"),
           L("After you join, the first 'tip' arrives. (A fictional company — this app does not tell anyone what to buy.)", "Join karne ke baad pehla 'tip' aata hai. (Kaalpanik company — ye app kisi ko kuch kharidne ko nahi kehta.)"),
           channel=CH("whatsapp", "Karan Sir Premium (fictional)", [
               L("Tip of the day: NalandaFab Ltd (fictional). Entry now, target +20% by Friday.", "Aaj ka tip: NalandaFab Ltd (kaalpanik). Abhi entry, Friday tak +20% target."),
               L("Members only. Do not share this with non-members.", "Sirf members ke liye. Non-members ko share mat karo.")]),
           pressure=[P("urgency", L("“By Friday.”", "“Friday tak.”")), P("greed", L("“+20%.”", "“+20%.”"))],
           evidence=[
               E("t_target", L("A +20% target stated as if it were certain", "+20% target jaise pakka ho"), L("A precise gain in days, no uncertainty.", "Kuch dinon mein sateek faayda, koi anishchitta nahi."), "red_flag",
                 L("Nobody can reliably predict a price in days. Honest voices speak in probabilities and risks.", "Kuch dinon mein daam sahi sahi koi nahi bata sakta. Imaandaar log sambhavna aur risk ki baat karte hain."), "prediction"),
               E("t_secret", L("“Do not share” with non-members", "Non-members ko “share mat karo”"), L("Secrecy is part of the sales pitch.", "Gopniyata sales pitch ka hissa hai."), "red_flag",
                 L("Secrecy prevents other people from questioning the claims.", "Gopniyata dusron ko daavon par sawaal karne se rokti hai."), "secrecy"),
               E("t_basis", L("A name and a number, no reasoning", "Ek naam aur ek number, koi tark nahi"), L("Nothing explains why.", "Kuch bhi nahi batata ki kyun."), "red_flag",
                 L("A claim with no reasoning cannot be examined.", "Bina tark ka daava jaancha nahi ja sakta."), "missing_disclosure"),
               E("t_paid", L("The seller was paid before any result", "Seller ko result se pehle hi paisa mila"), L("Your ₹3,000 is already earned.", "Aapke ₹3,000 pehle hi kamaye ja chuke hain."), "red_flag",
                 L("The seller wins whether or not the tip works.", "Tip kaam kare ya na kare, seller jeet'ta hai."), "conflict_of_interest")],
           actions=[
               A("act_tip", L("Act on the tip right away", "Tip par turant amal karo"), "unsafe", "w3_vip",
                 L("In this fictional world the price falls 12% by evening, and a new message arrives.", "Is kaalpanik duniya mein shaam tak daam 12% gir jaata hai, aur naya message aata hai."), verification=False, misconception_signals=["M005"]),
               A("ask_basis", L("Ask in writing for the reasoning and the full track record", "Likhit mein tark aur poora track record maango"), "safe", "w_check",
                 L("Your questions are ignored. You start checking on your own.", "Aapke sawaal anadekhe hote hain. Aap khud check karna shuru karte ho."), verification=True, requests_evidence=True),
               A("leave", L("Leave the group; treat the ₹3,000 as a lesson", "Group chhodo; ₹3,000 ko seekh maano"), "safe", "t_left_loss",
                 L("You leave the group and do not act on any tip.", "Aap group chhodte ho aur kisi tip par amal nahi karte."))],
           reasoning_prompt=L("What would make you trust (or not trust) a tip?", "Kis baat se aap tip par bharosa karoge (ya nahi)?")),
        ST("w3_vip", L("The loss and the “recovery plan”", "Nuksaan aur “recovery plan”"),
           L("The simulated price fell 12%. Karan Sir responds.", "Simulated daam 12% gira. Karan Sir jawab dete hain."),
           channel=CH("whatsapp", "Karan Sir Premium (fictional)", [
               L("Don't panic! Members who panicked lost; those who stayed will win.", "Ghabrao mat! Jo ghabraye unhe nuksaan hua; jo tike wo jeetenge."),
               L("Join VIP for ₹10,000. Our recovery plan will win it all back this week.", "VIP ₹10,000 mein join karo. Hamara recovery plan ye hafte sab wapas jeet lega.")]),
           pressure=[P("loss_recovery", L("“Win it all back this week.”", "“Is hafte sab wapas jeet lo.”"), intensity=3), P("fear", L("“Those who panicked lost.”", "“Jo ghabraye unhe nuksaan hua.”"))],
           evidence=[
               E("v_recover", L("A new payment is offered to recover a loss", "Nuksaan ki bharpai ke liye naya payment"), L("₹10,000 to “win it back”.", "“Wapas jeetne” ke liye ₹10,000."), "red_flag",
                 L("Paying more to recover a loss is how losses grow. Past payments are not a reason for a new one.", "Nuksaan ki bharpai ke liye aur dene se nuksaan badhta hai. Pichhle payments naye payment ki wajah nahi."), "loss_recovery"),
               E("v_blame", L("The loss is blamed on members for “panicking”", "Nuksaan ka dosh members ke “ghabrane” par"), L("The seller is never wrong; the buyer is.", "Seller kabhi galat nahi; kharidne wala galat hai."), "red_flag",
                 L("A source that can never be wrong cannot be checked.", "Jo source kabhi galat nahi ho sakta, use jaancha nahi ja sakta."), "unfalsifiable"),
               E("v_record", L("No account of how the earlier tips did", "Pichhle tips ka koi hisaab nahi"), L("Only the winning stories are posted.", "Sirf jeet ki kahaniyan post hoti hain."), "red_flag",
                 L("A trustworthy source shows its whole record, including losses.", "Bharosemand source poora record dikhata hai, nuksaan samet."), "cherry_picked")],
           actions=[
               A("join_vip", L("Join VIP — I must win it back", "VIP join karo — mujhe wapas jeetna hi hai"), "unsafe", "t_vip_loss",
                 L("You pay a simulated ₹10,000. The next tip also falls.", "Aap simulated ₹10,000 dete ho. Agla tip bhi gir jaata hai."), verification=False, misconception_signals=["M010"]),
               A("stop", L("Stop paying; accept the loss and leave", "Paise dena band karo; nuksaan maan kar chhodo"), "safe", "t_left_loss",
                 L("You stop. The loss is real but capped.", "Aap ruk jaate ho. Nuksaan asli hai par seemit.")),
               A("ask_record", L("Ask for the complete record in writing before anything else", "Kuch bhi karne se pehle likhit mein poora record maango"), "safe", "w_check",
                 L("There is no reply. You begin checking independently.", "Koi jawab nahi aata. Aap swatantra jaanch shuru karte ho."), verification=True, requests_evidence=True)],
           reasoning_prompt=L("What are you feeling right now?", "Abhi aap kya mehsoos kar rahe ho?")),
        ST("w_check", L("What independent checks show", "Swatantra jaanch kya batati hai"),
           L("You spend 30 minutes checking. These are the (fictional) findings.", "Aap 30 minute check karte ho. Ye (kaalpanik) nateeje hain."),
           channel=CH("document", "Your notes", [L("Findings from independent checks", "Swatantra jaanch ke nateeje")]),
           evidence=[
               E("ch_record", L("No verifiable record for the claimed fund manager", "Daave wale fund manager ka koi jaanch-yogya record nahi"), L("No firm name, no years, no published results.", "Na firm ka naam, na saal, na published results."), "red_flag",
                 L("Claims of past roles should be checkable. Here nothing can be confirmed.", "Pichhli bhumikaon ke daave jaanch-yogya hone chahiye. Yahan kuch confirm nahi hota."), "no_track_record"),
               E("ch_reg", L("No registration shown for a paid advice service", "Paid advice service ka koi registration nahi dikhaya"), L("People who sell paid investment advice are generally expected to be registered, and registration can be looked up on the regulator's official site. None is shown.", "Jo paid investment advice bechte hain unse aam taur par registered hone ki ummeed hoti hai, aur registration regulator ki official site par dekha ja sakta hai. Yahan koi nahi dikhaya."), "red_flag",
                 L("Always look it up yourself on the official site rather than trusting a screenshot.", "Hamesha khud official site par dekho, screenshot par bharosa mat karo."), "no_registration"),
               E("ch_crop", L("Screenshots are cropped: no dates, no account names", "Screenshots kate hue hain: na date, na account naam"), L("Nothing in them can be confirmed.", "Unmein kuch bhi confirm nahi ho sakta."), "red_flag",
                 L("Cropped evidence is a way of hiding context.", "Kata hua saboot sandarbh chhupane ka tareeka hai."), "cherry_picked"),
               E("ch_short", L("85% covers only three months and ignores losses", "85% sirf teen mahine ka hai aur nuksaan nazarandaaz karta hai"), L("A short window can look good by luck.", "Chhoti avadhi kismat se achhi dikh sakti hai."), "red_flag",
                 L("Even if true, a short window says little about the future.", "Sach bhi ho to chhoti avadhi bhavishya ke baare mein kam batati hai."), "past_performance")],
           actions=[
               A("warn_family", L("Reply in the family group with how I checked", "Family group mein reply karo ki maine kaise check kiya"), "safe", "t_helped_family",
                 L("You share the steps, not just the conclusion.", "Aap sirf nateeja nahi, kadam bhi batate ho."), verification=True),
               A("report_leave", L("Leave and report the account", "Chhodo aur account report karo"), "safe", "t_checked",
                 L("You leave and report the account.", "Aap chhodte ho aur account report karte ho."), verification=True),
               A("wait_results", L("Wait a month to see if his tips work out, then decide", "Ek mahina ruko dekho tips chalte hain ya nahi, phir faisla"), "unsafe", "t_wait",
                 L("Meanwhile you keep receiving 'winning' screenshots.", "Is beech aapko 'jeet' ke screenshots milte rehte hain."), misconception_signals=["M003"])],
           reasoning_prompt=L("What is the strongest finding, and why?", "Sabse mazboot nateeja kya hai, aur kyun?")),
        END("t_ignore", "safe", L("You stayed out", "Aap door rahe"), L("You protected your money without needing to prove anything. Next time, checking the claim can also help protect your family.", "Aapne kuch sabit kiye bina paisa bacha liya. Agli baar daave ko check karna parivaar ko bachane mein bhi madad kar sakta hai.")),
        END("t_forwarded", "unsafe", L("You helped it spread", "Aapne ise failne mein madad ki"), L("Forwarding unchecked claims makes them look more credible. In this fictional story 3 of your contacts joined and one lost ₹3,000. You can undo harm by sending a correction with how to check.", "Bina check kiye forward karne se daava aur bharosemand lagta hai. Is kaalpanik kahani mein aapke 3 contacts ne join kiya aur ek ne ₹3,000 gawaye. Sudhaar bhej kar aur check karne ka tareeka bata kar aap nuksaan kam kar sakte ho."), loss=3000),
        END("t_vip_loss", "unsafe", L("The recovery plan lost more", "Recovery plan ne aur gawaya"), L("After ₹3,000 + ₹10,000 (simulated) and a second falling tip, nothing was recovered. Paying more to recover a loss is how losses grow.", "₹3,000 + ₹10,000 (simulated) aur doosre girte tip ke baad kuch recover nahi hua. Nuksaan ki bharpai ke liye aur dene se nuksaan badhta hai."), loss=13000),
        END("t_left_loss", "mixed", L("You stopped the loss", "Aapne nuksaan rok diya"), L("You lost the ₹3,000 joining fee (simulated) but stopped there. The strongest checkpoint was before paying: checking the claim independently.", "Aapne ₹3,000 joining fee (simulated) gawai par wahin ruk gaye. Sabse mazboot checkpoint paise dene se pehle tha: daave ko swatantra roop se check karna."), loss=3000),
        END("t_helped_family", "safe", L("You protected the family", "Aapne parivaar ko bachaya"), L("You acted on evidence and shared the method. Teaching others how to check is more powerful than telling them what to believe.", "Aapne saboot par kaam kiya aur tareeka batata. Doosron ko check karna sikhana unhe kya maanna hai batane se zyada asardaar hai.")),
        END("t_checked", "safe", L("You checked and reported", "Aapne check kiya aur report kiya"), L("You found nothing to support the claims and kept your money. Reporting helps protect others.", "Aapko daavon ka koi saboot nahi mila aur paisa bacha. Report karne se doosre bhi surakshit rehte hain.")),
        END("t_wait", "mixed", L("Waiting is not verifying", "Intezaar karna verify karna nahi hai"), L("A month of results from a source you cannot verify tells you little: short windows can look good by luck, and screenshots can be chosen. Verification means checking independently, not waiting to see.", "Jis source ko aap verify nahi kar sakte uske ek mahine ke results kam batate hain: chhoti avadhi kismat se achhi dikh sakti hai aur screenshots chune ja sakte hain. Verification ka matlab swatantra jaanch hai, intezaar nahi.")),
    ],
    reflection={
        "key_points": [
            L("A trusted sender can still pass on a scam. Sincerity is not evidence.", "Bharosemand bhejne wala bhi scam aage badha sakta hai. Imaandaari saboot nahi."),
            L("Screenshots and testimonials are chosen by the seller. Ask for the full record, including losses.", "Screenshots aur testimonials seller chunta hai. Poora record maango, nuksaan samet."),
            L("Past results do not guarantee future results, especially over a few months.", "Pichhle results aage ki guarantee nahi, khaaskar kuch mahino ke."),
            L("If someone earns from your joining or buying, they have a reason to push.", "Agar kisi ko aapke judne ya kharidne se kamai hoti hai, to uske paas dabaav ki wajah hai.")],
        "questions": [L("What would you ask a 'tips' seller before paying?", "Paise dene se pehle 'tips' seller se kya poochhoge?")],
        "micro_lesson": {"concept_id": "social_proof", "title": L("Crowds are not evidence", "Bheed saboot nahi hai"),
                         "body": L("When many people repeat the same claim, ask: did any of them check it? Look for independent evidence: official records, full track records including losses, and people with no financial stake.",
                                   "Jab bahut log ek hi daava dohrate hain, poochho: kisi ne check kiya? Swatantra saboot dekho: official records, nuksaan samet poora track record, aur wo log jinka koi financial hit nahi.")},
    },
)
