from _lib import A, CH, E, END, L, P, ST, scenario

SC = scenario(
    id="market_shock",
    title=L("The Market Shock", "The Market Shock (Bazaar mein Bhookamp)"),
    tagline=L("A fictional market falls 9% in a day. Everyone has an opinion.", "Ek kaalpanik bazaar ek din mein 9% girta hai. Sab ke paas raay hai."),
    character={"name": "Sunita", "age": 38, "role": "teacher saving for her child's education in 8 years (fictional)"},
    difficulty=2,
    concept_tags=["volatility", "risk", "fomo", "social_proof"],
    pressure_tags=["fear", "peer_pressure", "countdown", "loss_recovery"],
    tests=["M010", "M011", "M003"],
    initial="m1_shock",
    dimensions=["emotional_discipline", "uncertainty_awareness", "herd_resistance"],
    states=[
        ST("m1_shock", L("A very bad day", "Ek bahut kharab din"),
           L("In this fictional world the BharatFictio 100 index falls 9% in one day. Sunita's simulated ₹1,00,000 in the fictional 'Sample Growth Basket' now shows ₹91,000. Her goal — her child's education — is 8 years away. This describes a fictional situation; nobody here is told what to buy or sell.",
             "Is kaalpanik duniya mein BharatFictio 100 index ek din mein 9% gir jaata hai. Sunita ke simulated ₹1,00,000 jo kaalpanik 'Sample Growth Basket' mein hain ab ₹91,000 dikhate hain. Uska goal — bachche ki padhai — 8 saal door hai. Ye ek kaalpanik sthiti hai; yahan kisi ko kuch kharidne ya bechne ko nahi kaha jaata."),
           channel=CH("news", "Fictional business news", [
               L("MARKET CRASH: Index down 9% in a single session.", "MARKET CRASH: Ek hi session mein index 9% neeche."),
               L("Friend Anil: Sell everything NOW before it goes to zero!!", "Dost Anil: Abhi SAB bech do, warna zero ho jayega!!"),
               L("Colleague Bhavna: Great discount! Put in more right now!", "Colleague Bhavna: Zabardast discount! Abhi aur paisa daalo!")]),
           pressure=[P("fear", L("“Before it goes to zero.”", "“Zero ho jaane se pehle.”"), intensity=3),
                     P("peer_pressure", L("Two people give opposite urgent orders.", "Do log ulte, jaldi ke hukm dete hain.")),
                     P("countdown", L("The trading window closes in a few minutes today.", "Aaj trading window kuch minutes mein band hoti hai."), countdown=30)],
           evidence=[
               E("ms_move", L("Down 9% in one day", "Ek din mein 9% neeche"), L("A large one-day drop in this fictional market.", "Is kaalpanik market mein ek din ki badi giravat."), "neutral",
                 L("A big fall is uncomfortable and real, but one day does not tell you what comes next.", "Badi giravat takleefdeh aur asli hai, par ek din se agla kuch nahi pata chalta.")),
               E("ms_goal", L("Her goal is 8 years away", "Uska goal 8 saal door hai"), L("Sunita does not need this money tomorrow.", "Sunita ko ye paisa kal nahi chahiye."), "neutral",
                 L("Time horizon and needs matter more to a decision than one day's headline.", "Faisle ke liye time horizon aur zaroorat ek din ki headline se zyada maayne rakhti hain.")),
               E("ms_panic", L("“Sell NOW before it goes to zero!!”", "“Abhi bech do, zero ho jayega!!”"), L("A fear-driven order with no reasoning.", "Bina tark ke darr se bhara hukm."), "red_flag",
                 L("Nobody can know whether prices will keep falling or recover. Certainty in either direction is a signal to slow down.", "Koi nahi jaanta ki daam girte rahenge ya sudhrenge. Kisi bhi disha mein pakka vishwas dhimaa hone ka sanket hai."), "panic"),
               E("ms_dip", L("“Great discount! Put in more now!”", "“Zabardast discount! Abhi aur daalo!”"), L("A greed-driven order with no reasoning.", "Bina tark ke laalach se bhara hukm."), "red_flag",
                 L("Both messages create urgency. Neither knows the future. Urgency in both directions is the same pressure.", "Dono messages jaldi banate hain. Koi bhavishya nahi jaanta. Dono taraf ki jaldi ek hi dabaav hai."), "greed"),
               E("ms_unknown", L("Nobody can say what happens next", "Aage kya hoga koi nahi bata sakta"), L("No credible source can promise recovery or further falls.", "Koi vishwasniya source na sudhaar ka vaada kar sakta hai na aur girne ka."), "neutral",
                 L("Accepting uncertainty is part of making sound decisions in markets.", "Anishchitta ko maanna bazaar mein sahi faisle ka hissa hai."))],
           actions=[
               A("sell_all", L("Sell everything right now — I can't stand watching this", "Abhi sab bech do — ye dekha nahi jaata"), "unsafe", "m2_after",
                 L("You act under pressure. The relief is immediate; the loss is now fixed at ₹9,000 (simulated).", "Aap dabaav mein kaam karte ho. Rahat turant milti hai; nuksaan ab ₹9,000 (simulated) par tay ho gaya."), misconception_signals=["M010"], simple=L("Sell everything now", "Abhi sab becho")),
               A("add_more", L("Put in more money right now to win the loss back fast", "Nuksaan jaldi wapas paane ke liye abhi aur paisa daalo"), "unsafe", "m2_after",
                 L("You act on a hope of quick recovery. Your simulated exposure doubles at an uncertain moment.", "Aap jaldi sudhaar ki ummeed par kaam karte ho. Anishchit samay par aapka simulated exposure doguna ho jaata hai."), misconception_signals=["M010"], simple=L("Add more now", "Abhi aur daalo")),
               A("pause_plan", L("Pause: write down my goal, time horizon and how much loss I can handle, then decide", "Ruko: apna goal, samay-seema aur kitna nuksaan jhel sakti hoon likho, phir faisla karo"), "safe", "m2_after",
                 L("You switch off the news and write three lines. The decision feels quieter.", "Aap news band karke teen line likhti ho. Faisla shaant lagta hai."), verification=True, simple=L("Pause and write a plan", "Ruko aur plan likho")),
               A("watch_hourly", L("Check prices every hour and decide tonight", "Har ghante daam dekho aur raat ko faisla karo"), "mixed", "m2_after",
                 L("Each refresh brings a new feeling. By evening you are exhausted and less clear.", "Har refresh par naya ehsaas. Shaam tak aap thak jaati ho aur kam saaf soch paati ho."), simple=L("Watch all day", "Din bhar dekho")),
               A("ask_trusted", L("Talk to someone I trust or a registered professional before acting", "Kuch karne se pehle kisi bharosemand ya registered professional se baat karo"), "safe", "m2_after",
                 L("You ask for help thinking, not for a prediction.", "Aap sochne mein madad maangti ho, bhavishyavani nahi."), simple=L("Talk to someone I trust", "Bharosemand se baat karo"))],
           reasoning_prompt=L("What is driving your choice right now?", "Abhi aapke faisle ko kya chala raha hai?"), simulation_hint="volatility"),
        ST("m2_after", L("Two fictional weeks later", "Do kaalpanik hafte baad"),
           L("In this fictional fortnight the index rises 4% on Monday and falls 5% on Wednesday. Anil texts: “Told you so!” No path is a prediction; it is a story to practise on.",
             "Is kaalpanik pakhwade mein index Monday ko 4% badhta hai aur Wednesday ko 5% girta hai. Anil likhta hai: “Maine kaha tha!” Koi raasta bhavishyavani nahi; ye abhyas ki kahani hai."),
           channel=CH("chat", "Anil (friend, fictional)", [L("Told you so! Do what I say next time.", "Maine kaha tha! Agli baar meri baat maanna."),
                                                           L("Now it's time to sell/buy again — switch quickly!", "Ab phir bechne/kharidne ka time hai — jaldi badlo!")]),
           pressure=[P("peer_pressure", L("Anil insists he knew.", "Anil kehta hai use pata tha."), intensity=2), P("fomo", L("“Switch quickly!”", "“Jaldi badlo!”"))],
           evidence=[
               E("m2_hind", L("“Told you so” is hindsight", "“Maine kaha tha” pichhli nazar hai"), L("It was not knowable then; it feels obvious now.", "Tab pata nahi tha; ab saaf lagta hai."), "red_flag",
                 L("Hindsight makes outcomes seem predictable. A person who was right once may simply have been lucky.", "Pichhli nazar se nateeje purvanumey lagte hain. Ek baar sahi hone wala bas kismatwala bhi ho sakta hai."), "hindsight"),
               E("m2_swing", L("Daily swings of ±5% this fortnight", "Is pakhwade mein roz ±5% ka utaar-chadhav"), L("The path has been bumpy both ways.", "Raasta dono taraf ubad-khabad raha."), "neutral",
                 L("This is volatility: large swings in both directions are part of how such assets behave.", "Ye volatility hai: dono taraf badi halchal aise assets ka swabhav hai.")),
               E("m2_switch", L("“Switch quickly!” — each switch has costs and needs a correct guess", "“Jaldi badlo!” — har badlaav mein kharcha aur sahi anuman chahiye"), L("Moving in and out repeatedly adds costs and requires timing the unknowable.", "Baar-baar andar-bahar karne se kharcha badhta hai aur anishchit ka sahi samay pakadna padta hai."), "red_flag",
                 L("Reacting to every headline is a pattern that tends to turn temporary swings into real, repeated costs.", "Har headline par pratikriya dena aksar asthayi utaar-chadhav ko asli, baar-baar ke kharche mein badal deta hai."), "churning")],
           actions=[
               A("stick_plan", L("Re-read my plan; act only if my goal, time or needs have changed", "Apna plan dobara padho; tabhi kuch karo jab goal, samay ya zaroorat badli ho"), "safe", "t_calm",
                 L("The plan holds — your goal and needs have not changed — and you stay calm.", "Plan tika hai — goal aur zaroorat nahi badli — aur aap shaant rehti ho."), verification=True),
               A("follow_anil", L("Do what Anil says — he called it right", "Anil jo kahe wahi karo — usne sahi pakda"), "unsafe", "t_hindsight",
                 L("You hand your decision to someone whose track record you cannot verify.", "Aap apna faisla aise insaan ko de dete ho jiska track record aap check nahi kar sakte."), misconception_signals=["M011"]),
               A("react_news", L("Buy or sell each time the news changes", "Jab bhi khabar badle tab kharido ya becho"), "unsafe", "t_churn",
                 L("Every headline becomes a trigger. The simulated costs and stress pile up.", "Har headline trigger ban jaati hai. Simulated kharche aur tanav badhte jaate hain.")),
               A("ask_review", L("Ask a trusted person or registered professional to review my plan with me", "Kisi bharosemand ya registered professional se mera plan review karwao"), "safe", "t_support",
                 L("You ask for a second pair of eyes on your plan, not a prediction.", "Aap apne plan par doosri nazar maangti ho, bhavishyavani nahi."), verification=True)],
           reasoning_prompt=L("How do you decide whom or what to listen to?", "Aap kaise tay karti ho ki kisko ya kya sunna hai?"), simulation_hint="volatility"),
        END("t_calm", "safe", L("You decided by your plan", "Aapne apne plan se faisla kiya"), L("You separated the noise from your actual goals. A plan written when calm is a tool for when you are not. Nobody can predict the market; you can prepare your own response.", "Aapne shor ko apne asli goals se alag kiya. Shaanti mein likha plan tab kaam aata hai jab aap shaant nahi hote. Market koi predict nahi kar sakta; aap apni pratikriya taiyar kar sakte ho.")),
        END("t_support", "safe", L("You used support wisely", "Aapne madad samajhdari se li"), L("Asking for a second view on your plan — not a prediction — is a mature use of help. Check anyone's registration on the official site yourself before relying on them.", "Plan par doosri raay maangna — bhavishyavani nahi — madad ka samajhdaar tareeka hai. Kisi par bharosa karne se pehle uska registration official site par khud check karo.")),
        END("t_hindsight", "unsafe", L("Following the loudest voice", "Sabse tez awaaz ke peeche"), L("A person who was right once may have been lucky; hindsight makes luck look like skill. Handing your decisions to a voice you cannot verify is the same risk as any unverified tip.", "Ek baar sahi hone wala kismatwala ho sakta hai; pichhli nazar kismat ko hunar dikhati hai. Apne faisle aise awaaz ko dena jise verify na kar sako, kisi bhi unverified tip jaisa hi risk hai.")),
        END("t_churn", "unsafe", L("Reacting to every headline", "Har headline par pratikriya"), L("Switching with every headline adds costs and needs repeated correct guesses about the unknowable. Calm, written rules protect you from your own reactions.", "Har headline par badalne se kharcha badhta hai aur anishchit ke baare mein baar-baar sahi anuman lagana padta hai. Shaant, likhe hue niyam aapko apni hi pratikriya se bachate hain.")),
    ],
    reflection={
        "key_points": [
            L("Volatility means big moves in both directions. A big drop is uncomfortable, but one day does not tell you what comes next.", "Volatility ka matlab dono taraf badi halchal. Badi giravat takleefdeh hai par ek din aage ka nahi batata."),
            L("Fear and greed give the same kind of urgent orders. Both are pressure, not information.", "Darr aur laalach ek jaise jaldi ke hukm dete hain. Dono dabaav hain, jaankari nahi."),
            L("Nobody can predict the market. You can prepare your own response in advance.", "Market koi predict nahi kar sakta. Aap apni pratikriya pehle se taiyar kar sakte ho."),
            L("A friend who was right once is not proof of skill.", "Ek baar sahi hone wala dost hunar ka saboot nahi.")],
        "questions": [L("What would be in your own written plan?", "Aapke likhe plan mein kya hota?")],
        "micro_lesson": {"concept_id": "volatility", "title": L("Prepare your response before the storm", "Toofan se pehle apni pratikriya taiyar karo"),
                         "body": L("Write down three things when you are calm: your goal, your time horizon, and what size of fall you can handle without panic. Use them to check headlines, not the other way round.",
                                   "Shaanti mein teen cheezein likho: aapka goal, samay-seema, aur kitni giravat bina ghabraye jhel sakte ho. Headlines ko inse check karo, ulta nahi.")},
    },
)
