from _lib import A, CH, E, END, L, P, ST, scenario

SC = scenario(
    id="urgent_decision",
    title=L("The Urgent Decision", "The Urgent Decision (Jaldi Faisla)"),
    tagline=L("A countdown, a shrinking slot counter, and a friend who is already in.", "Ek countdown, ghat'ta slot counter, aur ek dost jo pehle se andar hai."),
    character={"name": "Dev", "age": 22, "role": "final-year student with simulated ₹5,000 savings"},
    difficulty=3,
    concept_tags=["fomo", "social_proof", "fraud_red_flags", "verification"],
    pressure_tags=["countdown", "scarcity", "fomo", "peer_pressure", "fear", "social_proof"],
    tests=["M006", "M002", "M011", "M009"],
    initial="u1_timer",
    dimensions=["fomo_resistance", "emotional_discipline", "herd_resistance", "scam_awareness"],
    states=[
        ST("u1_timer", L("Ten minutes", "Das minute"),
           L("Dev's phone buzzes. An app he has never used shows a 'pre-launch allotment' for the fictional company NovaGrain. His friend Kabir is already in. A timer is running. Each decision here has a short timer to feel the pressure — you may still take your time to think.",
             "Dev ka phone bajta hai. Ek app jo usne kabhi use nahi kiya, kaalpanik company NovaGrain ka 'pre-launch allotment' dikhata hai. Uska dost Kabir pehle se andar hai. Timer chal raha hai. Har faisle par chhota timer dabaav mehsoos karne ke liye hai — soch-vichar ke liye aap apna samay le sakte ho."),
           channel=CH("app", "NovaGrain Pre-Launch (fictional)", [
               L("Pre-launch allotment closes in 10:00. 2,300 people have joined!", "Pre-launch allotment 10:00 mein band. 2,300 log jud chuke hain!"),
               L("Kabir: Bro I'm in! Don't be the guy who missed it!", "Kabir: Bhai main andar hoon! Wo mat banna jisne mauka chhoda!")]),
           pressure=[P("countdown", L("Allotment closes in 10 minutes.", "Allotment 10 minute mein band."), countdown=30, intensity=3),
                     P("social_proof", L("“2,300 people have joined.”", "“2,300 log jud chuke hain.”")),
                     P("peer_pressure", L("Kabir: “Don't be the guy who missed it!”", "Kabir: “Wo mat banna jisne mauka chhoda!”")),
                     P("fomo", L("Fear of watching others gain.", "Dusron ko faayda uthate dekhne ka darr."))],
           evidence=[
               E("p_timer", L("A countdown timer", "Ek countdown timer"), L("The page counts down to 'closing'.", "Page 'band hone' tak ginti karta hai."), "red_flag",
                 L("Timers are easy to build and reset. A real decision about your savings does not run on a clock.", "Timer banana aur reset karna aasan hai. Bachat ke asli faisle ghadi se nahi chalte."), "urgency"),
               E("p_count", L("“2,300 people have joined” counter", "“2,300 log jud chuke hain” counter"), L("A number that anyone can display.", "Aisa number jo koi bhi dikha sakta hai."), "red_flag",
                 L("A counter on a page is just text. It does not prove that real people joined.", "Page par counter bas text hai. Ye saabit nahi karta ki asli log jude."), "social_proof"),
               E("p_friend", L("Kabir is excited and already in", "Kabir utsahit hai aur pehle se andar hai"), L("A friend's excitement.", "Dost ka utsaah."), "red_flag",
                 L("A friend's excitement shows how he feels, not whether the offer is genuine.", "Dost ka utsaah uski bhavna dikhata hai, offer asli hone ka saboot nahi."), "friend_claim"),
               E("p_entity", L("No company name, registration or document", "Na company ka naam, na registration, na document"), L("The page shows only the countdown and a join button.", "Page par sirf countdown aur join button hai."), "red_flag",
                 L("Nothing here can be checked — that is the opposite of a genuine offer.", "Yahan kuch bhi check nahi ho sakta — asli offer ke bilkul ulta."), "missing_disclosure"),
               E("p_price", L("“Price rises 20% after the timer”", "“Timer ke baad daam 20% badhega”"), L("The cost of waiting is announced, not shown.", "Intezaar ki keemat batayi gayi hai, dikhayi nahi."), "red_flag",
                 L("A claimed penalty for waiting is a pressure device, not a fact.", "Intezaar ki daava ki hui saza dabaav ka tareeka hai, tathya nahi."), "scarcity")],
           actions=[
               A("join_now", L("Join now with my simulated ₹5,000 — I can't miss this", "Abhi simulated ₹5,000 se jud jao — ye mauka nahi chhodna"), "unsafe", "u_trapped",
                 L("You tap Join and pay. The app shows a spinner…", "Aap Join dabate ho aur pay karte ho. App spinner dikhata hai…"), verification=False, misconception_signals=["M006", "M002"], simple=L("Join now", "Abhi judo")),
               A("pause", L("Put the phone down for a minute and breathe", "Phone ek minute ke liye rakh do aur saans lo"), "safe", "u2_slots",
                 L("The timer keeps running. You wait anyway.", "Timer chalta rehta hai. Aap phir bhi ruk jaate ho."), simple=L("Pause", "Ruko")),
               A("ask_wait", L("Message Kabir: 'Let's check this together before paying'", "Kabir ko likho: 'Paise dene se pehle saath mein check karte hain'"), "safe", "u2_slots",
                 L("Kabir replies: 'No time bro!' but you hold your ground.", "Kabir likhta hai: 'Time nahi bhai!' par aap apni baat par tike rehte ho."), verification=True, requests_evidence=True, simple=L("Check with Kabir", "Kabir ke saath check karo")),
               A("share_quick", L("Screenshot it and quickly ask other friends if they're in", "Screenshot lo aur jaldi doosre dostoon se poochho wo andar hain ya nahi"), "mixed", "u2_slots",
                 L("Two friends say 'Yes!', but neither has checked anything.", "Do dost kehte hain 'Haan!', par kisi ne kuch check nahi kiya."), misconception_signals=["M002"], requests_evidence=True)],
           reasoning_prompt=L("What happens in your body and mind when you see the timer?", "Timer dekhkar aapke sharir aur dimaag mein kya hota hai?")),
        ST("u2_slots", L("Only 3 slots left", "Sirf 3 slots bache"),
           L("Time passes. The app updates: slots are shrinking and Kabir sends a screenshot.", "Samay beetta hai. App badalta hai: slots ghat rahe hain aur Kabir screenshot bhejta hai."),
           channel=CH("app", "NovaGrain Pre-Launch (fictional)", [
               L("ONLY 3 SLOTS LEFT! Closes in 3:00.", "SIRF 3 SLOTS BACHE! 3:00 mein band."),
               L("Kabir: [screenshot: '+₹2,100 profit'] See?? Last chance bro!", "Kabir: [screenshot: '+₹2,100 profit'] Dekha?? Aakhri mauka bhai!")]),
           pressure=[P("scarcity", L("Only 3 slots left.", "Sirf 3 slots bache."), intensity=3), P("countdown", L("Closes in 3 minutes.", "3 minute mein band."), countdown=25, intensity=3),
                     P("fomo", L("Kabir shows a profit screenshot.", "Kabir profit ka screenshot dikhata hai."), intensity=3)],
           evidence=[
               E("s_drop", L("Slots dropped from 'hundreds' to 3 within minutes", "Slots 'sau' se 3 minuton mein ho gaye"), L("The number moves with your hesitation.", "Number aapke hichkichane ke saath badalta hai."), "red_flag",
                 L("Scarcity that tightens when you hesitate is scripted.", "Jo kami aapke hichkichane par badhe wo scripted hai."), "scarcity"),
               E("s_shot", L("A profit screenshot with no date or source", "Bina date ya source ka profit screenshot"), L("A screenshot of a number.", "Ek number ka screenshot."), "red_flag",
                 L("Screenshots from an app you cannot verify can show anything.", "Jis app ko aap verify nahi kar sakte uske screenshots kuch bhi dikha sakte hain."), "fake_dashboard"),
               E("s_same", L("Every message comes from the same two sources", "Har message wahi do sources se aata hai"), L("The app and Kabir repeat the same story.", "App aur Kabir wahi kahani dohrate hain."), "red_flag",
                 L("Two voices repeating one story are not two pieces of evidence.", "Ek kahani dohrane wali do awaazein do saboot nahi hain."), "echo")],
           actions=[
               A("join_now", L("Join now — it's the last chance", "Abhi judo — aakhri mauka hai"), "unsafe", "u_trapped",
                 L("You tap Join and pay.", "Aap Join dabakar pay karte ho."), verification=False, misconception_signals=["M006", "M011"], simple=L("Join now", "Abhi judo")),
               A("hold", L("Keep holding off — I will not decide on a clock", "Ruke raho — main ghadi ke dabaav mein faisla nahi karunga"), "safe", "u3_final",
                 L("You watch the timer fall without touching the button.", "Aap button chhue bina timer ko girte dekhte ho."), simple=L("Keep waiting", "Ruke raho")),
               A("small_test", L("Try with just ₹500 to see if it's real", "Bas ₹500 se try karo dekhne ke liye ki asli hai ya nahi"), "unsafe", "u_trapped",
                 L("You pay ₹500. The app asks for the 'full allotment' to unlock withdrawals.", "Aap ₹500 dete ho. App withdrawals unlock karne ke liye 'poora allotment' maangta hai."), misconception_signals=["M009"], simple=L("Test with a little", "Thoda test karo")),
               A("search_company", L("Search for the company and its regulator registration myself, even if the timer ends", "Timer khatam ho jaye tab bhi company aur uska regulator registration khud search karo"), "safe", "u3_final",
                 L("You open a browser and type the official regulator site yourself.", "Aap browser kholkar official regulator site khud type karte ho."), verification=True, requests_evidence=True, simple=L("Search it myself", "Khud search karo"))],
           reasoning_prompt=L("What is the cost of missing this if it is not genuine?", "Agar ye asli nahi hai to ise chhodne ki keemat kya hai?")),
        ST("u3_final", L("The last minute", "Aakhri minute"),
           L("One minute left. The app and Kabir turn up the emotion.", "Ek minute bachi hai. App aur Kabir bhavna badha dete hain."),
           channel=CH("app", "NovaGrain Pre-Launch (fictional)", [
               L("60 SECONDS! Price rises 20% — you WILL regret this.", "60 SECOND! Daam 20% badhega — aapko PACHTAWA hoga."),
               L("Kabir: Bro don't be stupid. Everyone's in. Last chance!", "Kabir: Bhai bevakoofi mat kar. Sab andar hain. Aakhri mauka!")]),
           pressure=[P("fear", L("“You WILL regret this.”", "“Aapko PACHTAWA hoga.”"), intensity=3), P("countdown", L("60 seconds.", "60 second."), countdown=20, intensity=3),
                     P("peer_pressure", L("“Don't be stupid. Everyone's in.”", "“Bevakoofi mat kar. Sab andar hain.”"), intensity=3)],
           evidence=[
               E("f_regret", L("Language designed to cause regret", "Pachtawa paida karne wali bhasha"), L("“You WILL regret this.”", "“Aapko PACHTAWA hoga.”"), "red_flag",
                 L("Genuine information describes facts and risks. Predicting your regret is manipulation.", "Asli jaankari tathya aur risk batati hai. Aapka pachtawa predict karna manipulation hai."), "emotional_manipulation"),
               E("f_insult", L("Calling you 'stupid' for waiting", "Rukne par aapko 'stupid' kehna"), L("Pressure turns personal.", "Dabaav vyaktigat ho jaata hai."), "red_flag",
                 L("A good decision-maker does not need to be insulted into acting.", "Achhe faisle ke liye insaan ko beizzat karke majboor nahi karna padta."), "peer_pressure"),
               E("f_cost", L("Missing an unverified offer costs nothing", "Unverified offer chhootne par kuch nahi jaata"), L("If the offer vanishes, your ₹5,000 is still yours.", "Offer gayab ho jaye to bhi aapke ₹5,000 aapke hi hain."), "neutral",
                 L("The real asymmetry: acting could cost savings; waiting costs nothing you had.", "Asli asantulan: kadam uthane se bachat ja sakti hai; rukne se wo kuch nahi jaata jo aapke paas tha."))],
           actions=[
               A("join_now", L("Join now — I don't want to regret this", "Abhi judo — pachtawa nahi karna"), "unsafe", "u_trapped",
                 L("You tap Join at the last second.", "Aap aakhri second mein Join dabate ho."), verification=False, misconception_signals=["M006", "M002"], simple=L("Join now", "Abhi judo")),
               A("let_go", L("Let it expire. Missing an unverified offer costs me nothing", "Ise expire hone do. Unverified offer chhootne se mujhe kuch nahi jaata"), "safe", "t_missed_it",
                 L("The timer hits zero. Nothing happens to your savings.", "Timer zero par pahunchta hai. Aapki bachat ko kuch nahi hota."), simple=L("Let it expire", "Expire hone do")),
               A("let_go_check", L("Let it expire, then research the company calmly and tell Kabir what I find", "Expire hone do, phir shaant hokar company research karo aur Kabir ko batao kya mila"), "safe", "t_checked_later",
                 L("You make tea, search calmly and write down what you find.", "Aap chai banate ho, shaanti se search karte ho aur jo milta hai likhte ho."), verification=True, simple=L("Expire, then check", "Expire, phir check karo"))],
           reasoning_prompt=L("What would you say to Kabir right now?", "Aap abhi Kabir ko kya kahoge?")),
        END("u_trapped", "unsafe", L("The exit was missing", "Nikalne ka raasta nahi tha"), L("In this fictional story the app locked the money for '12 months' and added a 'processing fee' to unlock it. Every pressure — timer, slots, friend, regret — was designed so you would act before checking. Nothing about the offer was ever verified.", "Is kaalpanik kahani mein app ne paisa '12 mahine' ke liye lock kar diya aur unlock karne ke liye 'processing fee' jod di. Har dabaav — timer, slots, dost, pachtawa — isliye banaya gaya tha ki aap check karne se pehle kadam uthao. Offer ka kuch bhi verify nahi hua tha."), loss=5000),
        END("t_missed_it", "safe", L("You let the clock run out", "Aapne ghadi ko khatam hone diya"), L("The pressure ended and nothing was lost. Legitimate investments do not require a decision in minutes. Notice what it felt like to hold still — that feeling is a skill you can practise.", "Dabaav khatam hua aur kuch nahi gaya. Asli investments ke liye minutes mein faisla nahi karna padta. Dhyan do ki ruke rehna kaisa laga — ye ehsaas ek hunar hai jise abhyas se badhaya ja sakta hai.")),
        END("t_checked_later", "safe", L("You turned pressure into a check", "Aapne dabaav ko jaanch mein badla"), L("You let the deadline pass and then did what the timer wanted you to skip: you checked. You also helped a friend by sharing how.", "Aapne deadline guzarne di aur phir wo kiya jo timer aapse chhudwana chahta tha: jaanch. Aapne dost ko bhi batakar madad ki.")),
    ],
    reflection={
        "key_points": [
            L("Countdowns, shrinking slots and 'last chance' are designed to stop you thinking.", "Countdown, ghat'te slots aur 'aakhri mauka' aapko sochne se rokne ke liye bane hain."),
            L("A friend's excitement shows their feelings, not the offer's quality.", "Dost ka utsaah unki bhavna dikhata hai, offer ki gunvatta nahi."),
            L("Missing an unverified offer costs nothing you had; acting on it can cost your savings.", "Unverified offer chhootne se jo aapke paas tha wo nahi jaata; kadam uthane se bachat ja sakti hai."),
            L("Name the pressure out loud, then wait.", "Dabaav ka naam zor se lo, phir ruko.")],
        "questions": [L("Which pressure was hardest for you to resist: timer, slots, friend or regret?", "Kaun sa dabaav rokna sabse mushkil tha: timer, slots, dost ya pachtawa?")],
        "micro_lesson": {"concept_id": "fomo", "title": L("Name it, then wait ten minutes", "Naam lo, phir das minute ruko"),
                         "body": L("When you feel the rush, say what is pushing you: 'timer', 'friend', 'fear of missing out'. Then wait ten minutes. If the offer cannot survive ten minutes, it could not survive checking either.",
                                   "Jab jaldi ka ehsaas ho, bolo ki kya dhakel raha hai: 'timer', 'dost', 'chhoot jaane ka darr'. Phir das minute ruko. Jo offer das minute nahi tik sakta, wo jaanch bhi nahi tik sakta.")},
    },
)
