from _lib import A, CH, E, END, L, ST, P, scenario


def obs(v: float) -> list[dict]:
    return [{"dimension": "terminology", "value": v}]


SC = scenario(
    id="confusing_document",
    title=L("The Confusing Document", "The Confusing Document (Uljhe Hue Kaagaz)"),
    tagline=L("A summary full of jargon. Understanding comes before signing.", "Jargon se bhara summary. Samajhna pehle, sign karna baad mein."),
    character={"name": "Gopal", "age": 64, "role": "retired clerk reading a fund summary (fictional)"},
    difficulty=2,
    concept_tags=["financial_disclosures", "nav", "mutual_fund", "bond", "fees"],
    pressure_tags=["authority", "emotional_story"],
    tests=["M008", "M005", "M012", "M001"],
    initial="d1_doc",
    dimensions=["terminology", "concept_knowledge", "independent_reasoning"],
    states=[
        ST("d1_doc", L("The summary", "Summary"),
           L("Gopal receives a 'Scheme Information Summary' for the fictional Aakash Debt Opportunities Fund. The agent is patient and polite. Gopal does not understand many terms. All details are fictional.",
             "Gopal ko kaalpanik Aakash Debt Opportunities Fund ka 'Scheme Information Summary' milta hai. Agent dhairyavaan aur vinamra hai. Gopal ko kai shabd samajh nahi aate. Sab vivaran kaalpanik hain."),
           channel=CH("document", "Aakash Debt Opportunities Fund — summary (fictional)", [
               L("Open-ended debt scheme investing across instruments with a Macaulay duration of 3–4 years.", "Open-ended debt scheme jo 3–4 saal ki Macaulay duration wale instruments mein nivesh karti hai."),
               L("Indicative YTM: 7.2% (not a guarantee).  NAV: ₹12.4510.", "Indicative YTM: 7.2% (guarantee nahi).  NAV: ₹12.4510."),
               L("Exit load: 1% if redeemed within 12 months.", "Exit load: 12 mahine ke andar nikalne par 1%."),
               L("Riskometer: Moderately High. Credit risk: lower-rated instruments may default.", "Riskometer: Moderately High. Credit risk: kam rating wale instruments default kar sakte hain.")]),
           pressure=[P("authority", L("An official-looking document and a confident agent.", "Official dikhne wala document aur aatmavishwasi agent."))],
           evidence=[
               E("x_credit", L("“Credit risk: may default”", "“Credit risk: default kar sakte hain”"), L("Some of what the fund holds may fail to repay.", "Fund ke kuch instruments wapas na chuka sakte hain."), "red_flag",
                 L("This is a plain risk statement hidden in jargon. 'Debt' does not mean 'safe'.", "Ye jargon mein chhupa seedha risk-kathan hai. 'Debt' ka matlab 'surakshit' nahi."), "credit_risk"),
               E("x_exit", L("“Exit load 1% within 12 months”", "“12 mahine ke andar Exit load 1%”"), L("A charge for taking money out early.", "Jaldi paisa nikalne par ek charge."), "red_flag",
                 L("This affects how freely you can use your money in the first year.", "Ye pehle saal mein aap apna paisa kitni aazadi se use kar sakte ho, use prabhavit karta hai."), "exit_load"),
               E("x_ytm", L("“Indicative YTM 7.2% (not a guarantee)”", "“Indicative YTM 7.2% (guarantee nahi)”"), L("An estimated yield with a disclaimer.", "Disclaimer ke saath ek anumaanit yield."), "red_flag",
                 L("'Indicative' and 'not a guarantee' mean this is an estimate, not a promise.", "'Indicative' aur 'guarantee nahi' ka matlab ye anuman hai, vaada nahi."), "estimate_vs_promise"),
               E("x_meter", L("“Riskometer: Moderately High”", "“Riskometer: Moderately High”"), L("A label of the product's risk level.", "Product ke risk star ka label."), "red_flag",
                 L("The product itself tells you the risk is not low.", "Product khud batata hai ki risk kam nahi hai."), "risk_label"),
               E("x_jargon", L("Dense jargon like “Macaulay duration”", "“Macaulay duration” jaisa ghana jargon"), L("Terms that sound expert.", "Aise shabd jo visheshagya jaise lagte hain."), "neutral",
                 L("Technical words do not make something trustworthy. You may ask for plain-language explanations.", "Technical shabd kisi cheez ko bharosemand nahi banate. Aap saral bhasha mein samjhane ko keh sakte ho."))],
           actions=[
               A("sign", L("Sign — it looks official and the agent is so patient", "Sign karo — official lagta hai aur agent itna dhairyavaan hai"), "unsafe", "t_signed_blind",
                 L("You sign without understanding the key terms.", "Aap mukhya shabd samjhe bina sign karte ho."), verification=False, misconception_signals=["M008"], simple=L("Sign it", "Sign karo")),
               A("circle_terms", L("Circle every term I don't understand and ask for plain explanations", "Har shabd jo samajh na aaye usse gher kar saral bhasha mein samjhane ko kaho"), "safe", "d2_nav",
                 L("You circle six terms. The agent explains the first few.", "Aap chhe shabdon par ghera lagate ho. Agent pehle kuch samjhata hai."), verification=True, requests_evidence=True, simple=L("Circle what I don't understand", "Jo samajh na aaye usse gher lo")),
               A("only_ytm", L("Look only at 7.2% — that's the number that matters", "Sirf 7.2% dekho — wahi number zaroori hai"), "unsafe", "d2_nav",
                 L("You focus on the biggest number and skip the rest.", "Aap sabse bade number par dhyan dete ho aur baaki chhod dete ho."), misconception_signals=["M005"], simple=L("Look only at 7.2%", "Sirf 7.2% dekho")),
               A("ask_family", L("Ask my daughter to read it with me tonight", "Aaj raat beti ke saath padho"), "safe", "d2_nav",
                 L("The agent says 'no time!' but you take it home.", "Agent kehta hai 'time nahi!' par aap ghar le jaate ho."), verification=True, requests_evidence=True, simple=L("Read it with family", "Parivaar ke saath padho"))],
           reasoning_prompt=L("What is your first reaction to this document?", "Is document par aapki pehli pratikriya kya hai?")),
        ST("d2_nav", L("What is NAV?", "NAV kya hai?"),
           L("Gopal asks about 'NAV ₹12.4510'. The agent says: “Low NAV means it's cheap — a good time to join!” How should Gopal understand NAV?",
             "Gopal 'NAV ₹12.4510' ke baare mein poochta hai. Agent kehta hai: “Kam NAV matlab sasta hai — judne ka achha waqt!” Gopal ko NAV kaise samajhna chahiye?"),
           channel=CH("chat", "Agent (fictional)", [L("Low NAV = cheap = good time!", "Kam NAV = sasta = achha waqt!")]),
           pressure=[P("authority", L("An expert says it confidently.", "Ek visheshagya aatmavishwas se kehta hai."))],
           evidence=[E("n_claim", L("“Low NAV means cheap”", "“Kam NAV matlab sasta”"), L("A claim that sounds like a shortcut.", "Ek shortcut jaisa lagne wala daava."), "red_flag",
                       L("NAV is the value per unit, not a price tag for quality. A ₹10 NAV and a ₹100 NAV can grow equally.", "NAV ek unit ki keemat hai, gunvatta ka daam nahi. ₹10 aur ₹100 NAV barabar badh sakte hain."), "nav_misconception")],
           actions=[
               A("nav_correct", L("NAV is the value of one unit (assets minus liabilities, divided by units). A low number does not mean cheap or better", "NAV ek unit ki keemat hai (assets minus liabilities, units se bhaag). Kam number ka matlab sasta ya behtar nahi"), "safe", "d3_exit",
                 L("Exactly. NAV is a measurement, not a forecast.", "Bilkul. NAV ek naap hai, bhavishyavani nahi."), observations=obs(92), concept_tags=["nav"]),
               A("nav_cheap", L("A low NAV means the fund is cheap, so it is a better deal", "Kam NAV matlab fund sasta hai, to behtar sauda hai"), "unsafe", "d3_exit",
                 L("This is a common mix-up between per-unit value and quality.", "Ye per-unit keemat aur gunvatta ke beech ki aam galatfehmi hai."), misconception_signals=["M005"], observations=obs(10), concept_tags=["nav"]),
               A("nav_return", L("NAV is the return I will get", "NAV wo return hai jo mujhe milega"), "unsafe", "d3_exit",
                 L("NAV is a value on a date; it says nothing about what you will earn.", "NAV ek tareekh ka mulya hai; ye nahi batata ki aap kitna kamaoge."), misconception_signals=["M001"], observations=obs(10), concept_tags=["nav"])],
           reasoning_prompt=L("Explain NAV in your own words.", "NAV ko apne shabdon mein samjhao.")),
        ST("d3_exit", L("What does exit load mean for me?", "Exit load mere liye kya hai?"),
           L("Gopal might need ₹20,000 for house repairs in six months. The summary says “Exit load: 1% if redeemed within 12 months”. What does that mean for him?",
             "Gopal ko chhe mahine mein ghar ki marammat ke liye ₹20,000 chahiye ho sakte hain. Summary kehta hai “Exit load: 12 mahine ke andar nikalne par 1%”. Iska uske liye kya matlab hai?"),
           channel=CH("document", "Summary extract", [L("Exit load: 1% if redeemed within 12 months.", "Exit load: 12 mahine ke andar nikalne par 1%.")]),
           evidence=[E("l_when", L("The charge depends on how long he stays", "Charge is par nirbhar hai ki wo kitne samay rukta hai"), L("Taking money out in month 6 triggers it.", "Mahine 6 mein paisa nikalne par lagta hai."), "neutral",
                       L("Exit load links to liquidity: it is the cost of needing your money early.", "Exit load liquidity se judta hai: ye jaldi paise ki zaroorat ki keemat hai."))],
           actions=[
               A("exit_correct", L("If I take money out within the first year, 1% of the amount I withdraw is deducted", "Pehle saal ke andar paisa nikalun to nikali gayi rakam ka 1% kat jaayega"), "safe", "d4_yield",
                 L("Yes: an exit load is a charge on leaving early.", "Haan: exit load jaldi nikalne par ek charge hai."), observations=obs(92), concept_tags=["fees", "liquidity"]),
               A("exit_fail", L("It is a fee only if the fund does badly", "Ye fee sirf tab hai jab fund kharab chale"), "unsafe", "d4_yield",
                 L("It applies based on timing, not on performance.", "Ye samay par lagu hota hai, performance par nahi."), misconception_signals=["M012"], observations=obs(10), concept_tags=["fees"]),
               A("exit_entry", L("It is the fee for entering; it has nothing to do with withdrawing", "Ye entering ki fee hai; nikalne se iska koi lena-dena nahi"), "unsafe", "d4_yield",
                 L("An 'exit' load is charged on exit, not entry.", "'Exit' load nikalte samay lagta hai, pravesh par nahi."), misconception_signals=["M012"], observations=obs(15), concept_tags=["fees"])],
           reasoning_prompt=L("When might this matter for Gopal?", "Gopal ke liye ye kab maayne rakhega?")),
        ST("d4_yield", L("Is 7.2% guaranteed?", "Kya 7.2% guaranteed hai?"),
           L("The agent says: “It gives 7.2% — better than a bank deposit!” Gopal wonders if 7.2% is guaranteed.", "Agent kehta hai: “Ye 7.2% deta hai — bank deposit se behtar!” Gopal sochta hai kya 7.2% guaranteed hai."),
           channel=CH("chat", "Agent (fictional)", [L("It gives 7.2% — better than a bank deposit!", "Ye 7.2% deta hai — bank deposit se behtar!")]),
           pressure=[P("authority", L("An expert compares it with a bank deposit.", "Ek visheshagya ise bank deposit se tulna karta hai."))],
           evidence=[E("y_ind", L("The document says “indicative” and “not a guarantee”", "Document “indicative” aur “guarantee nahi” kehta hai"), L("The agent's words and the document differ.", "Agent ke shabd aur document alag hain."), "red_flag",
                       L("When the agent's words differ from the document, trust the document and ask for clarification.", "Jab agent ke shabd document se alag hon, document par bharosa karo aur spashtikaran maango."), "estimate_vs_promise")],
           actions=[
               A("yield_correct", L("No — 'indicative YTM' is an estimate, not a promise. Credit risk and costs can change what I actually get", "Nahi — 'indicative YTM' anuman hai, vaada nahi. Credit risk aur kharche mujhe milne wali asli rakam badal sakte hain"), "safe", "d5_decide",
                 L("Correct. An estimate printed in a document is still an estimate.", "Sahi. Document mein chhapa anuman phir bhi anuman hai."), observations=obs(92), concept_tags=["bond", "risk"]),
               A("yield_fixed", L("Yes, it is printed in the document, so it is fixed", "Haan, document mein chhapa hai, to tay hai"), "unsafe", "d5_decide",
                 L("Printed does not mean promised — read 'indicative' and 'not a guarantee'.", "Chhapa hona vaada hona nahi — 'indicative' aur 'guarantee nahi' padho."), misconception_signals=["M001", "M007"], observations=obs(10), concept_tags=["bond", "risk"]),
               A("yield_ignore", L("I can't tell anything from this document, so ignore it completely", "Is document se kuch samajh nahi aata, to ise bilkul ignore karo"), "mixed", "d5_decide",
                 L("Not understanding is a reason to ask, not to ignore.", "Na samajhna poochhne ki wajah hai, ignore karne ki nahi."), observations=obs(45), concept_tags=["financial_disclosures"])],
           reasoning_prompt=L("What is the difference between an estimate and a promise?", "Anuman aur vaade mein kya fark hai?")),
        ST("d5_decide", L("How to proceed", "Aage kaise badhein"),
           L("Gopal now decides how to proceed with the document and the agent.", "Gopal ab document aur agent ke saath aage badhne ka tareeka tay karta hai."),
           channel=CH("none", None, []),
           actions=[
               A("take_time", L("Take three days, get plain-language answers to what I can lose, when I can withdraw and what all the costs are — and decide only when I can explain it myself", "Teen din lo, saral bhasha mein jawab pao: mera kitna nuksaan ho sakta hai, kab nikal sakta hoon, aur sabhi kharche kya hain — aur tabhi faisla karo jab khud samjha sakun"), "safe", "t_confident",
                 L("You write three questions and your own summary.", "Aap teen sawaal aur apna summary likhte ho."), verification=True, simple=L("Take time and ask", "Samay lo aur poochho")),
               A("sign_trust", L("Sign today because the agent has been patient with me", "Aaj sign karo kyunki agent ne mere saath dhairya rakha"), "unsafe", "t_signed_blind",
                 L("Politeness is not evidence of suitability.", "Vinamrata upyuktata ka saboot nahi."), misconception_signals=["M008"], simple=L("Sign today", "Aaj sign karo")),
               A("ask_three", L("Ask the agent: 'What can I lose? When can I withdraw? What are all the costs?' and write down the answers", "Agent se poochho: 'Mera kya kho sakta hai? Kab nikal sakta hoon? Sabhi kharche kya hain?' aur jawab likh lo"), "safe", "t_confident",
                 L("You get written answers to three clear questions.", "Aapko teen saaf sawaalon ke likhit jawab milte hain."), verification=True, requests_evidence=True, simple=L("Ask three questions", "Teen sawaal poochho"))],
           reasoning_prompt=L("What will you need before you are ready to decide?", "Faisla karne se pehle aapko kya chahiye?")),
        END("t_confident", "safe", L("You can explain it in your own words", "Aap ise apne shabdon mein samjha sakte ho"), L("You decided to understand before signing. If you cannot explain the risks, costs and withdrawal rules in your own words, you are not ready to sign — and that is a perfectly good answer.", "Aapne sign karne se pehle samajhna chuna. Agar aap risk, kharche aur nikalne ke niyam apne shabdon mein nahi samjha sakte, to aap sign karne ke liye taiyar nahi — aur ye ek bilkul sahi jawab hai.")),
        END("t_signed_blind", "unsafe", L("Signed without understanding", "Bina samjhe sign kiya"), L("You signed because the document looked official and the agent seemed kind. Jargon and politeness are not evidence. Many people discover exit loads, credit risk and costs only after signing — you can ask before.", "Aapne sign kiya kyunki document official dikhta tha aur agent dayalu lagta tha. Jargon aur vinamrata saboot nahi hain. Kai log exit load, credit risk aur kharche sign karne ke baad hi jaante hain — aap pehle pooch sakte ho."), loss=300),
    ],
    reflection={
        "key_points": [
            L("Jargon is not credibility. You have the right to plain-language explanations.", "Jargon bharosemandi nahi hai. Aapko saral bhasha mein samjhne ka adhikar hai."),
            L("NAV is a per-unit value, not a measure of 'cheap' or 'good'.", "NAV per-unit keemat hai, 'sasta' ya 'achha' ka paimana nahi."),
            L("Exit load is a cost of leaving early; it links to liquidity.", "Exit load jaldi nikalne ki keemat hai; ye liquidity se judta hai."),
            L("An 'indicative' yield is an estimate, not a promise.", "'Indicative' yield anuman hai, vaada nahi.")],
        "questions": [L("Which term would you ask someone to explain first?", "Aap sabse pehle kis shabd ko samjhane ko kahoge?")],
        "micro_lesson": {"concept_id": "financial_disclosures", "title": L("The three questions to ask before signing", "Sign karne se pehle teen sawaal"),
                         "body": L("1) What can I lose? 2) When and how can I withdraw, and at what cost? 3) What are ALL the charges, in rupees? If you cannot get clear written answers, do not sign yet.",
                                   "1) Mera kitna nuksaan ho sakta hai? 2) Kab aur kaise nikal sakta hoon, kitne kharche par? 3) SABHI charges rupees mein kya hain? Agar saaf likhit jawab na mile to abhi sign mat karo.")},
    },
)
