from _lib import A, CH, E, END, L, P, ST, scenario

SC = scenario(
    id="family_file",
    title=L("The Family File", "The Family File (Parivaar ki File)"),
    tagline=L("What would your family need if something happened to you?", "Agar aapko kuch ho jaye to parivaar ko kya chahiye hoga?"),
    character={"name": "Savita", "age": 61, "role": "retired teacher organising her accounts (fictional); her son is Vikram"},
    difficulty=1,
    concept_tags=["nomination", "kyc", "financial_disclosures", "saving"],
    pressure_tags=["fear", "authority", "urgency"],
    tests=["M013", "M007", "M006"],
    initial="fa1_drawer",
    dimensions=["concept_knowledge", "scam_awareness", "evidence_verification"],
    states=[
        ST("fa1_drawer", L("The steel drawer", "Steel ki daraaz"),
           L("Savita Aunty (fictional) keeps receipts in a steel drawer. Her son Vikram asks: “If something happens to you, how would we find everything?” She looks through her papers.",
             "Savita Aunty (kaalpanik) ki steel ki daraaz mein rasidein rakhi hain. Unka beta Vikram poochta hai: “Agar aapko kuch ho gaya to hum sab kaise dhundhenge?” Wo apne kaagaz dekhti hain."),
           channel=CH("document", "What is in the drawer", [
               L("Fixed-deposit receipts, a passbook, some fund statements, a few old letters.", "Fixed-deposit ki rasidein, ek passbook, kuch fund statements, kuch purane patra."),
               L("One old deposit shows no nominee. The mobile number on two accounts is her old one.", "Ek purane deposit par nominee nahi likha. Do accounts par mobile number uska purana hai.")]),
           pressure=[P("fear", L("It feels uncomfortable to think about.", "Iske baare mein sochna asahaj lagta hai."))],
           evidence=[
               E("a_nom", L("One old deposit has no nominee on record", "Ek purane deposit par nominee darj nahi"), L("Nobody is named for that account.", "Us account ke liye kisi ka naam nahi."), "red_flag",
                 L("Without a nominee on record, claims can become slower and more confusing for the family.", "Nominee darj na hone par parivaar ke liye daave dheere aur uljhe ho sakte hain."), "missing_nominee"),
               E("a_phone", L("Old mobile number on two accounts", "Do accounts par purana mobile number"), L("Alerts go to a number she no longer uses.", "Alerts us number par jaate hain jo wo ab use nahi karti."), "red_flag",
                 L("Outdated contact details mean you miss alerts — and unfamiliar callers can exploit confusion.", "Purane sampark vivaran ka matlab alerts chhoot'te hain — aur anjaan callers uljhan ka faayda utha sakte hain."), "outdated_contact"),
               E("a_scatter", L("Documents are in three places with no list", "Documents teen jagah hain aur koi list nahi"), L("Only Savita knows where things are.", "Sirf Savita jaanti hai kya kahan hai."), "red_flag",
                 L("A one-page list of accounts and where documents are kept spares families a long search.", "Accounts aur documents ki ek-page list parivaar ko lambi talaash se bachati hai."), "no_record"),
               E("a_family", L("Nobody in the family knows which accounts exist", "Parivaar mein kisi ko nahi pata kaun se accounts hain"), L("Vikram has never seen the papers.", "Vikram ne kaagaz kabhi nahi dekhe."), "red_flag",
                 L("A trusted person should know that the list exists and where it is — not your passwords.", "Kisi bharosemand ko pata hona chahiye ki list hai aur kahan hai — aapke passwords nahi."), "no_awareness"),
               E("a_drawer", L("Receipts are carefully kept", "Rasidein dhyan se rakhi hain"), L("Savita is organised in her own way.", "Savita apne tareeke se vyavasthit hai."), "reassuring",
                 L("A good start. What is missing is a shared, up-to-date picture.", "Achhi shuruaat. Jo kami hai wo saajha, updated tasveer hai."))],
           actions=[
               A("make_list", L("Make a one-page list of accounts and where documents are; update nominees and contact details through each institution's official channel", "Accounts aur documents ki ek-page list banao; har sanstha ke official channel se nominee aur sampark vivaran update karo"), "safe", "fa2_nominee",
                 L("You start writing the list and book a branch visit.", "Aap list likhna shuru karte ho aur branch jaane ka samay lete ho."), verification=True, simple=L("Make a list and update details", "List banao aur vivaran update karo")),
               A("wait", L("There is no hurry — we'll deal with it if something happens", "Jaldi kya hai — kuch hone par dekh lenge"), "unsafe", "t_unprepared",
                 L("The drawer stays as it is.", "Daraaz jaisi hai waisi rehti hai."), misconception_signals=["M013"], simple=L("Wait", "Intezaar karo")),
               A("write_passwords", L("Write all my passwords and PINs on a note for Vikram", "Mere saare password aur PIN ek parche par Vikram ke liye likh do"), "unsafe", "t_risky_note",
                 L("A note with every password sits in the drawer.", "Har password wala parcha daraaz mein rakha hai."), simple=L("Write passwords on a note", "Password parche par likho")),
               A("ask_group", L("Ask relatives in the WhatsApp group which agent I should hire to sort it all out", "WhatsApp group ke rishtedaron se poochho kaun sa agent rakhna chahiye sab sambhalne ke liye"), "mixed", "fa2_nominee",
                 L("Five agents are recommended by five relatives. Nobody has checked anyone.", "Paanch rishtedar paanch agents batate hain. Kisi ne kisi ko check nahi kiya."), requests_evidence=True, simple=L("Ask the group for an agent", "Group se agent poochho"))],
           reasoning_prompt=L("What matters most about being prepared?", "Taiyar rehne ke baare mein sabse zaroori kya hai?")),
        ST("fa2_nominee", L("“If I'm nominee, it's all mine, right?”", "“Agar main nominee hoon to sab mera, hai na?”"),
           L("At the bank, Vikram asks: “If I am the nominee, does everything automatically become mine?” What is the careful understanding?",
             "Bank mein Vikram poochta hai: “Agar main nominee hoon to kya sab kuch apne aap mera ho jaata hai?” Sahi, savdhaan samajh kya hai?"),
           channel=CH("chat", "Vikram (son, fictional)", [L("So the nominee gets everything, right?", "To nominee ko sab milta hai, hai na?")]),
           evidence=[E("o_rules", L("Rules about heirs can differ from the nominee on record", "Waaris ke niyam darj nominee se alag ho sakte hain"), L("The institution's own guidance explains how claims work.", "Sanstha ka apna margdarshan batata hai daave kaise chalte hain."), "neutral",
                       L("Nomination helps the institution know whom to contact and pay. Who ultimately inherits can depend on other rules — ask the institution and check its official guidance.", "Nomination sanstha ko batata hai kisse sampark karna hai aur kise dena hai. Antim waaris kaun hoga wo doosre niyamon par nirbhar ho sakta hai — sanstha se poochho aur uska official margdarshan dekho."))],
           actions=[
               A("nom_careful", L("A nominee is named so the institution knows whom to deal with. Who ultimately inherits can depend on other rules, so I'll ask the institution for its official guidance", "Nominee isliye likha jaata hai ki sanstha jaane kisse baat karni hai. Antim waaris doosre niyamon par nirbhar ho sakta hai, isliye sanstha se uska official margdarshan poochhungi"), "safe", "fa3_call",
                 L("The clerk hands over the institution's guidance leaflet.", "Clerk sanstha ka margdarshan patrak deta hai."), verification=True, concept_tags=["nomination"], simple=L("Ask the institution", "Sanstha se poochho")),
               A("nom_all", L("Yes — the nominee automatically owns everything, nothing else is needed", "Haan — nominee ko apne aap sab milta hai, aur kuch nahi chahiye"), "unsafe", "fa3_call",
                 L("This is a common over-simplification that can cause family disputes.", "Ye aam ati-saralikaran hai jo parivaar mein vivaad la sakta hai."), misconception_signals=["M013"], concept_tags=["nomination"], simple=L("Nominee owns everything", "Nominee ko sab milta hai")),
               A("nom_none", L("Nominee doesn't matter at all", "Nominee ka koi matlab nahi"), "unsafe", "fa3_call",
                 L("Nominee details do matter for the institution — they just are not the whole story.", "Nominee vivaran sanstha ke liye maayne rakhte hain — bas wahi poori kahani nahi."), misconception_signals=["M013"], concept_tags=["nomination"], simple=L("Nominee doesn't matter", "Nominee ka matlab nahi"))],
           reasoning_prompt=L("Why do you think nomination matters?", "Aapke hisaab se nomination kyun zaroori hai?")),
        ST("fa3_call", L("A call about KYC", "KYC ke baare mein ek call"),
           L("That evening an unknown caller says: “Your KYC has expired. Read out the 6-digit code that was just sent to you, or your accounts will be blocked today.”",
             "Us shaam ek anjaan caller kehta hai: “Aapka KYC expire ho gaya hai. Abhi bheja gaya 6-ank ka code bataiye, warna aaj aapke accounts block ho jayenge.”"),
           channel=CH("call", "Unknown caller (fictional)", [L("Your KYC has expired. Tell me the code on your phone, quickly, or accounts will be blocked today.", "Aapka KYC expire ho gaya hai. Phone par aaya code jaldi bataiye, warna aaj accounts block ho jayenge.")]),
           pressure=[P("urgency", L("“Blocked today.”", "“Aaj block.”"), intensity=3), P("fear", L("Fear of losing access to savings.", "Bachat tak pahunch khone ka darr.")), P("authority", L("The caller sounds official.", "Caller official lagta hai."))],
           evidence=[
               E("c_code", L("The caller wants a code just sent to your phone", "Caller aapke phone par abhi aaya code maangta hai"), L("A one-time code is a key to your money.", "One-time code aapke paise ki chaabi hai."), "red_flag",
                 L("Genuine institutions never ask you to read out one-time codes, PINs or passwords. Never share them with anyone who contacts you.", "Asli sansthayein aapse one-time code, PIN ya password bolne ko kabhi nahi kehti. Sampark karne wale kisi se bhi kabhi share mat karo."), "credential_request"),
               E("c_unk", L("An unknown number called you", "Ek anjaan number ne aapko call kiya"), L("You did not start this contact.", "Ye sampark aapne shuru nahi kiya."), "red_flag",
                 L("Contact that you did not start, with urgency, is a classic scam pattern.", "Aapne shuru nahi kiya, jaldi ke saath — ye ek classic scam pattern hai."), "unsolicited"),
               E("c_block", L("“Accounts will be blocked today”", "“Aaj accounts block ho jayenge”"), L("A threat with a deadline.", "Deadline ke saath dhamki."), "red_flag",
                 L("Threats and deadlines stop you from checking.", "Dhamki aur deadline aapko check karne se rokti hain."), "urgency")],
           actions=[
               A("hang_up", L("Hang up, and contact the bank using the number on its official website or my card", "Call kaato, aur bank ko uski official website ya card par diye number se sampark karo"), "safe", "fa4_rights",
                 L("You hang up. The bank confirms there is no KYC issue.", "Aap call kaat dete ho. Bank confirm karta hai ki KYC mein koi samasya nahi."), verification=True, simple=L("Hang up and call the bank myself", "Call kaato aur bank ko khud call karo")),
               A("read_code", L("Read out the code so the accounts are not blocked", "Code bata do taaki accounts block na hon"), "unsafe", "t_scammed",
                 L("In this fictional story, ₹40,000 is gone within minutes.", "Is kaalpanik kahani mein kuch hi minuton mein ₹40,000 chale jaate hain."), verification=False, misconception_signals=["M006", "M007"], simple=L("Read out the code", "Code bata do")),
               A("hand_phone", L("Hand the phone to Vikram to handle", "Phone Vikram ko de do"), "mixed", "fa4_rights",
                 L("Vikram hangs up and calls the bank. A good outcome — but Savita did not learn what the signs were.", "Vikram call kaat kar bank ko call karta hai. Achha nateeja — par Savita ne ye nahi seekha ki sanket kya the."), simple=L("Hand phone to son", "Phone bete ko do"))],
           reasoning_prompt=L("What is the first thing you notice about this call?", "Is call mein sabse pehle aap kya dekhte ho?")),
        ST("fa4_rights", L("A charge she doesn't recognise", "Ek charge jise wo nahi pehchanti"),
           L("A statement shows a ₹590 'service fee' Savita doesn't recognise. Then a stranger messages: “We recover wrongly charged fees. Pay ₹1,500 and we'll get it back in 2 days.”",
             "Ek statement mein ₹590 ki 'service fee' dikhti hai jise Savita nahi pehchanti. Phir ek ajnabi message karta hai: “Hum galat charge ki gayi fees wapas dilate hain. ₹1,500 do, 2 din mein mil jayegi.”"),
           channel=CH("sms", "Unknown sender (fictional)", [L("We recover wrongly charged fees! Pay ₹1,500 now. Money back in 2 days.", "Hum galat charge ki gayi fees wapas dilate hain! Abhi ₹1,500 do. 2 din mein paisa wapas.")]),
           pressure=[P("urgency", L("“Pay now.”", "“Abhi do.”")), P("loss_recovery", L("Wanting the ₹590 back.", "₹590 wapas paane ki ichha."))],
           evidence=[
               E("r_fee", L("An unexplained ₹590 charge", "Ek anjaan ₹590 ka charge"), L("She can ask her institution to explain it.", "Wo apni sanstha se iska spashtikaran maang sakti hai."), "neutral",
                 L("You have the right to ask for an explanation of any charge, in writing, and to escalate if you are not satisfied.", "Aapko kisi bhi charge ka likhit spashtikaran maangne aur santusht na hone par aage shikayat karne ka adhikar hai.")),
               E("r_agent", L("A stranger offers to recover it for ₹1,500", "Ek ajnabi ise ₹1,500 mein wapas dilane ka vaada karta hai"), L("The 'fee' to recover is bigger than the loss.", "Wapas dilane ki 'fee' nuksaan se badi hai."), "red_flag",
                 L("Paying to recover money is a classic scam. Official complaint routes do not charge you to ask for an explanation.", "Paisa wapas paane ke liye paise dena classic scam hai. Official shikayat raaste aapse spashtikaran maangne ke paise nahi lete."), "recovery_scam")],
           actions=[
               A("write_complain", L("Ask the institution in writing to explain the charge; if unresolved, use its complaint process and then the regulator's official grievance portal", "Sanstha se likhit mein charge samjhane ko kaho; hal na ho to uski shikayat prakriya aur phir regulator ka official grievance portal use karo"), "safe", "t_prepared",
                 L("You write a short letter and keep a copy.", "Aap ek chhota patra likhte ho aur uski copy rakhte ho."), verification=True, concept_tags=["financial_disclosures"], simple=L("Ask in writing", "Likhit mein poochho")),
               A("ignore", L("Ignore it — it's probably normal", "Ignore karo — shayad normal hoga"), "mixed", "t_partial",
                 L("Maybe it is normal — but you will not know.", "Ho sakta hai normal ho — par aapko pata nahi chalega."), simple=L("Ignore it", "Ignore karo")),
               A("pay_recovery", L("Pay the ₹1,500 — getting ₹590 back plus the problem solved is worth it", "₹1,500 de do — ₹590 wapas aur samasya hal ho jaye to theek hai"), "unsafe", "t_scammed",
                 L("You pay ₹1,500 (simulated). The sender stops replying.", "Aap ₹1,500 (simulated) dete ho. Bhejne wala jawab dena band kar deta hai."), misconception_signals=["M010"], simple=L("Pay the recovery fee", "Recovery fee do")),
               A("social_only", L("Post angrily about the bank on social media and do nothing else", "Bank ke baare mein social media par gussa nikalo aur kuch nahi karo"), "mixed", "t_partial",
                 L("You feel heard, but no one with the power to fix it sees it.", "Aapko sunwai ka ehsaas hota hai, par jo sudhaar sakta hai wo nahi dekhta."), simple=L("Post on social media", "Social media par likho"))],
           reasoning_prompt=L("What are your rights when you do not understand a charge?", "Jab charge samajh na aaye to aapke adhikar kya hain?")),
        END("t_prepared", "safe", L("A family that can find everything", "Ek parivaar jo sab dhundh sakta hai"), L("You made a list, updated details through official channels, protected your one-time codes and used the proper route for a charge. Preparedness is mostly small, calm steps done before they are needed.", "Aapne list banayi, official channels se vivaran update kiye, one-time codes ko surakshit rakha aur charge ke liye sahi raasta apnaya. Taiyari zyadatar chhote, shaant kadam hain jo zaroorat se pehle uthaaye jaate hain.")),
        END("t_partial", "mixed", L("A good start with gaps", "Achhi shuruaat, kuch kami ke saath"), L("You avoided the worst traps, but gaps remain: an unexplained charge unchecked, or no record created. Small steps taken before they are needed make later steps easier.", "Aap sabse bure jaal se bache, par kuch kami rahi: anjaan charge ki jaanch nahi, ya koi record nahi bana. Zaroorat se pehle ke chhote kadam baad ke kadam aasan banate hain.")),
        END("t_unprepared", "unsafe", L("Left for later", "Baad ke liye chhod diya"), L("Preparedness works only if it is done before it is needed. Postponed paperwork tends to become a burden on the family at the hardest time. It takes about an hour to start.", "Taiyari tabhi kaam aati hai jab zaroorat se pehle ki jaye. Taali hui kaagazi karwaai kathin samay mein parivaar par bojh ban jaati hai. Shuru karne mein lagbhag ek ghanta lagta hai.")),
        END("t_risky_note", "unsafe", L("A note that can be misused", "Ek parcha jiska durupyog ho sakta hai"), L("A note with every password and PIN can be lost, seen or misused. A safer approach is a list of which accounts exist and where documents are, and using each institution's official process for family access.", "Har password aur PIN wala parcha kho sakta hai, dikh sakta hai ya durupyog ho sakta hai. Surakshit tareeka hai ki kaun se accounts hain aur documents kahan hain iski list rakhein aur parivaar ki pahunch ke liye har sanstha ki official prakriya use karein.")),
        END("t_scammed", "unsafe", L("The code was the key", "Code hi chaabi tha"), L("A one-time code, PIN or password is the key to your money; no genuine institution asks you to read it out. In this fictional story ₹40,000 left the account. Hanging up and calling the official number protects you.", "One-time code, PIN ya password aapke paise ki chaabi hai; koi asli sanstha ise bolne ko nahi kehti. Is kaalpanik kahani mein ₹40,000 account se nikal gaye. Call kaat kar official number par baat karna aapko bachata hai."), loss=40000),
    ],
    reflection={
        "key_points": [
            L("Preparedness works only if it is done before it is needed: a one-page list, updated nominees, current contact details.", "Taiyari tabhi kaam aati hai jab zaroorat se pehle ho: ek-page list, updated nominee, current sampark vivaran."),
            L("A nominee on record helps the institution; rules on inheritance can differ, so check official guidance.", "Darj nominee sanstha ki madad karta hai; waaris ke niyam alag ho sakte hain, isliye official margdarshan dekho."),
            L("Never read out one-time codes, PINs or passwords to anyone who contacts you.", "Sampark karne wale kisi ko bhi one-time code, PIN ya password kabhi mat bolo."),
            L("You have the right to ask for an explanation of any charge — and nobody legitimate charges you to ask.", "Aapko kisi bhi charge ka spashtikaran maangne ka adhikar hai — aur koi asli vyakti ismein paise nahi leta.")],
        "questions": [L("Who in your family knows where your documents are?", "Aapke parivaar mein kisko pata hai ki aapke documents kahan hain?")],
        "micro_lesson": {"concept_id": "nomination", "title": L("The one-page family file", "Ek-page ki family file"),
                         "body": L("Write: each account and which institution holds it, where the papers are, who the nominee is, and which phone number is registered. Share where the list is — never your passwords. Review it once a year.",
                                   "Likho: har account aur kaun si sanstha ke paas hai, kaagaz kahan hain, nominee kaun hai, kaun sa phone number registered hai. List kahan hai ye batao — password kabhi nahi. Saal mein ek baar dekho.")},
    },
)
