"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_category'), ['category'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('verified_official', sa.Boolean(), nullable=False),
    sa.Column('published_date', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_key')
    )
    op.create_table('misconceptions',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('data_version', sa.String(length=60), nullable=False),
    sa.Column('synthetic_data', sa.Boolean(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_version')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_name'), ['name'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('concept_tags', sa.JSON(), nullable=False),
    sa.Column('pressure_tags', sa.JSON(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('concept_tags', sa.JSON(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=40), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('simple_mode', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("language in ('en','hinglish','hi')", name='ck_user_language'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_token_hash'), ['token_hash'], unique=True)

    op.create_table('adaptive_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weakness', sa.String(length=60), nullable=True),
    sa.Column('selected_training', sa.String(length=80), nullable=False),
    sa.Column('training_kind', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('mastery_estimate', sa.Float(), nullable=True),
    sa.Column('predicted_success', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adaptive_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adaptive_selections_user_id'), ['user_id'], unique=False)

    op.create_table('dimension_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=40), nullable=True),
    sa.Column('note', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value >= 0 and value <= 100', name='ck_obs_value'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dimension_observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_user_dim', ['user_id', 'dimension'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=120), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_doc_chunk')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('concept_id', sa.String(length=40), nullable=True),
    sa.Column('misconception_id', sa.String(length=8), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['misconception_id'], ['misconceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_misconception_id'), ['misconception_id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('concept_id', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_concept_id'), ['concept_id'], unique=False)

    op.create_table('resilience_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resilience_scores', schema=None) as batch_op:
        batch_op.create_index('ix_score_user_dim_time', ['user_id', 'dimension', 'created_at'], unique=False)

    op.create_table('scenario_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=60), nullable=False),
    sa.Column('state_key', sa.String(length=60), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'state_key', name='uq_scenario_state')
    )
    with op.batch_alter_table('scenario_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_states_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('simulation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.String(length=40), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_events_simulation_id'), ['simulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_events_user_id'), ['user_id'], unique=False)

    op.create_table('training_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('data_version', sa.String(length=60), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_runs_model_name'), ['model_name'], unique=False)

    op.create_table('user_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=40), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('mastery >= 0 and mastery <= 1', name='ck_mastery_range'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_user_concept')
    )
    with op.batch_alter_table('user_concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_concepts_user_id'), ['user_id'], unique=False)

    op.create_table('user_misconceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('misconception_id', sa.String(length=8), nullable=False),
    sa.Column('detections', sa.Integer(), nullable=False),
    sa.Column('exposures', sa.Integer(), nullable=False),
    sa.Column('clean_streak', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['misconception_id'], ['misconceptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'misconception_id', name='uq_user_misconception')
    )
    with op.batch_alter_table('user_misconceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_misconceptions_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=60), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('misconception_id', sa.String(length=8), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('scenario_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=60), nullable=False),
    sa.Column('scenario_version', sa.Integer(), nullable=False),
    sa.Column('current_state_key', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('path', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('selection_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['selection_id'], ['adaptive_selections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_sessions_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenario_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_session_user_status', ['user_id', 'status'], unique=False)

    op.create_table('scenario_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state_key', sa.String(length=60), nullable=False),
    sa.Column('action_id', sa.String(length=60), nullable=False),
    sa.Column('action_quality', sa.String(length=10), nullable=False),
    sa.Column('next_state_key', sa.String(length=60), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('pressure_types', sa.JSON(), nullable=False),
    sa.Column('countdown_expired', sa.Boolean(), nullable=False),
    sa.Column('evidence_noticed', sa.JSON(), nullable=False),
    sa.Column('evidence_missed', sa.JSON(), nullable=False),
    sa.Column('evidence_requested', sa.JSON(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence is null or (confidence >= 1 and confidence <= 5)', name='ck_confidence_range'),
    sa.ForeignKeyConstraint(['session_id'], ['scenario_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_decisions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenario_decisions_user_id'), ['user_id'], unique=False)

    op.create_table('decision_reasoning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('safety_flags', sa.JSON(), nullable=False),
    sa.Column('behaviours', sa.JSON(), nullable=False),
    sa.Column('misconceptions', sa.JSON(), nullable=False),
    sa.Column('emotional_indicators', sa.JSON(), nullable=False),
    sa.Column('uncertainty_recognized', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_source', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['scenario_decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_reasoning')
    with op.batch_alter_table('scenario_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_scenario_decisions_session_id'))

    op.drop_table('scenario_decisions')
    with op.batch_alter_table('scenario_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_user_status')
        batch_op.drop_index(batch_op.f('ix_scenario_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_scenario_sessions_scenario_id'))

    op.drop_table('scenario_sessions')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_user_id'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('user_misconceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_misconceptions_user_id'))

    op.drop_table('user_misconceptions')
    with op.batch_alter_table('user_concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_concepts_user_id'))

    op.drop_table('user_concepts')
    with op.batch_alter_table('training_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_runs_model_name'))

    op.drop_table('training_runs')
    with op.batch_alter_table('simulation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_events_simulation_id'))

    op.drop_table('simulation_events')
    with op.batch_alter_table('scenario_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_states_scenario_id'))

    op.drop_table('scenario_states')
    with op.batch_alter_table('resilience_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_score_user_dim_time')

    op.drop_table('resilience_scores')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_concept_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_misconception_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_concept_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('dimension_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_obs_user_dim')

    op.drop_table('dimension_observations')
    with op.batch_alter_table('adaptive_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adaptive_selections_user_id'))

    op.drop_table('adaptive_selections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_token_hash'))
        batch_op.drop_index(batch_op.f('ix_users_public_id'))

    op.drop_table('users')
    op.drop_table('simulations')
    op.drop_table('scenarios')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_name'))

    op.drop_table('model_versions')
    op.drop_table('misconceptions')
    op.drop_table('knowledge_documents')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_category'))

    op.drop_table('concepts')
    # ### end Alembic commands ###
